import fs from "node:fs";
import crypto from "node:crypto";
import assert from "node:assert/strict";
const [alpacaPath, selfPath] = process.argv.slice(2);
assert.ok(alpacaPath && selfPath, "Two pinned source files required");
const review = JSON.parse(fs.readFileSync("artifacts/compositional-intent-graph-v1/CIG-02E_SYNTHETIC_FULL_INPUT_REVIEW.json", "utf8"));
const matrix = JSON.parse(fs.readFileSync(review.parent_matrix, "utf8"));
const selected = matrix.topics.flatMap(t => t.source_rows.filter(r => r.decision === "SUPPLEMENTAL_SYNTHETIC_REVIEW_PENDING").map(r => ({topic_id:t.topic_id,source_row:r.source_row,instruction_sha256:r.instruction_sha256})));
assert.equal(selected.length, 26);
assert.deepEqual(review.decisions.map(r => ({topic_id:r.topic_id,source_row:r.source_row,instruction_sha256:r.instruction_sha256})), selected);
const bytes = {alpaca:fs.readFileSync(alpacaPath),self_instruct:fs.readFileSync(selfPath)};
const rows = {alpaca:JSON.parse(bytes.alpaca.toString("utf8")),self_instruct:bytes.self_instruct.toString("utf8").trim().split(/\r?\n/u).map(JSON.parse)};
const hash = s => crypto.createHash("sha256").update(s).digest("hex");
for (const key of Object.keys(rows)) assert.equal(rows[key].length, review.sources[key].rows);
const identities = review.decisions.map(d => {
  const [key,id] = d.source_row.split(":");
  assert.ok(Object.hasOwn(rows,key) && /^[1-9][0-9]*$/.test(id));
  const row = rows[key][Number(id)-1];
  assert.equal(typeof row.instruction,"string"); assert.equal(typeof row.input,"string");
  assert.equal(hash(row.instruction.trim()),d.instruction_sha256,"Immutable queue instruction mismatch");
  return {topic_id:d.topic_id,source_row:d.source_row,instruction_sha256:hash(row.instruction.trim()),input_sha256:hash(row.input),instruction_input_sha256:hash(JSON.stringify([row.instruction,row.input]))};
});
const counts = review.decisions.reduce((a,d) => {a[d.decision]=(a[d.decision]||0)+1;return a;},{});
assert.deepEqual(counts,review.decision_counts);
assert.equal(new Set(identities.map(d=>d.source_row)).size,25);
assert.equal(review.accepted_fixture_rows,0);assert.equal(review.gold_rows_created,0);
assert.equal(review.cig02_frozen,false);assert.equal(review.cig03_started,false);
const result={classification:"SYNTHETIC_SOURCE_IDENTITY_ONLY_NOT_GOLD_OR_CAPABILITY",nominations:26,distinct_source_rows:25,source_sha256:Object.fromEntries(Object.entries(bytes).map(([k,v])=>[k,hash(v)])),identities,accepted_gold_rows:0,cig02_frozen:false};
fs.mkdirSync("artifacts/ci",{recursive:true});
fs.writeFileSync("artifacts/ci/cig02e-synthetic-review-identities.json",JSON.stringify(result,null,2)+"\n");
console.log(JSON.stringify(result));
