import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {reviewDigest,validateDevelopmentReviewJournal} from './development_review_journal.mjs';
const root=new URL('../../',import.meta.url),read=p=>readFile(new URL(p,root),'utf8'),json=async p=>JSON.parse(await read(p)),sha=s=>createHash('sha256').update(s).digest('hex');
test('822 actual memberships preserve768 records/96 pair receipts;54 CAL source reviews admit no calibration or capability',async()=>{
 const registry=await json('data/zero_model_refoundation/development/development_review_registry_v0.1.json'),prefix=await json('data/zero_model_refoundation/development/development_review_journal_v0.9.json'),journal=await json('data/zero_model_refoundation/development/development_review_journal_v0.10.json'),result=await json('docs/zero-model-refoundation-v1/ZMR-03_DEV_V04_CAL_SLICE1_REVIEW_RESULT.json');
 assert.deepEqual(journal.records.slice(0,768),prefix.records);assert.deepEqual(journal.safety_pair_review_records,prefix.safety_pair_review_records);assert.equal(journal.safety_pair_review_records.length,96);assert.equal(journal.prefix_tail_sha256,'3499acc89fb754a02fa0366d4e0b24767a1c4eaae25632f212d1dd11d93cb5a0');assert.equal(journal.prefix_journal_sha256,reviewDigest(prefix));
 const catalog=await read('catalog/system_topic_catalog_v0.2.yaml');assert.equal(sha(catalog),registry.catalog_sha256);const topics=[...catalog.matchAll(/^  - topic_id: (.+)$/gm)].map(x=>x[1]);assert.equal(topics.length,144);
 const paths=[1,2,3,4,5].map(n=>'data/zero_model_refoundation/development/provisional_tune_v0.4_slice'+n+'.json').concat('data/zero_model_refoundation/development/provisional_safety_v0.4_seed.json','data/zero_model_refoundation/development/provisional_safety_v0.4_remaining.json','data/zero_model_refoundation/development/provisional_cal_v0.4_slice1.json'),packets=await Promise.all(paths.map(async path=>({path,utf8:await read(path)}))),rows=packets.flatMap(p=>JSON.parse(p.utf8).rows),cal=JSON.parse(packets[7].utf8);
 const audit=validateDevelopmentReviewJournal({registry,journal,topics,packets});for(const [k,v] of Object.entries(audit))assert.deepEqual(result[k],v,k);assert.equal(result.journal_sha256,reviewDigest(journal));assert.deepEqual(result.source_packet_pins,packets.map(p=>({path:p.path,sha256:sha(p.utf8)})));
 assert.deepEqual(journal.records.map(r=>r.row_id),rows.map(r=>r.row_id));assert.equal(rows.length,822);assert.equal(result.reviewed_rows,822);assert.equal(result.unreviewed_registered_rows,378);assert.deepEqual(result.dispositions,{LABEL_IDENTIFIABILITY_HOLD:74,PROPOSE_REVISION:492,RETAIN_PROVISIONAL:256});assert.equal(new Set(rows.flatMap(r=>r.provisional_gold_topics)).size,144);assert.equal(result.reviewed_topics,144);
 const languages={};for(const r of rows)languages[r.language]=(languages[r.language]??0)+1;assert.deepEqual(result.reviewed_language_counts,languages);assert.deepEqual(languages,{zh:274,en:274,mixed:274});
 const suffix=journal.records.slice(768);assert.equal(suffix.length,54);assert.deepEqual(suffix.map(r=>r.row_id),cal.rows.map(r=>r.row_id));assert.equal(new Set(cal.rows.map(r=>r.topic_id)).size,18);assert(cal.rows.every(r=>r.split==='CAL_PROVISIONAL'&&r.expected_state==='ASSIGNED'&&r.title===''&&r.recent.length===0));assert.equal(cal.candidate_prediction_exposures,0);assert.equal(cal.evaluation_status,'UNRUN_NO_ROUTER_PREDICTIONS');
 const dispositions={};for(const r of suffix)dispositions[r.disposition]=(dispositions[r.disposition]??0)+1;assert.deepEqual(result.new_dispositions,dispositions);assert.deepEqual(dispositions,{PROPOSE_REVISION:41,RETAIN_PROVISIONAL:10,LABEL_IDENTIFIABILITY_HOLD:3});assert.deepEqual(suffix.filter(r=>r.disposition==='LABEL_IDENTIFIABILITY_HOLD').map(r=>r.row_id),['034','035','036'].map(x=>'cal-v04-s1-'+x));
 for(const r of suffix){assert.deepEqual(r.original_annotation.provisional_gold_topics,r.proposed_annotation.provisional_gold_topics);assert.deepEqual(r.original_annotation.excluded_topics,r.proposed_annotation.excluded_topics);assert.equal(r.original_annotation.expected_state,r.proposed_annotation.expected_state);assert.equal(r.revision,1);assert.equal(r.independent,false);assert.equal(r.reviewer_role,'CANDIDATE_WRITER');for(const k of ['qualification_credit','candidate_prediction_exposures','semantic_evaluations'])assert.equal(r[k],0);assert.equal(r.calibration_admission,'HOLD_SOURCE_GOLD_MECHANISM_REVIEW_AND_ACCOUNTING');
  assert.deepEqual(r.proposed_annotation.provisional_evidence_spans.filter(s=>s.role==='OBJECT'),r.original_annotation.provisional_evidence_spans.filter(s=>s.role==='OBJECT'));
  assert.equal(new Set(r.proposed_annotation.provisional_evidence_spans.map(s=>reviewDigest(s))).size,r.proposed_annotation.provisional_evidence_spans.length);
  if(r.disposition==='PROPOSE_REVISION'){const old=r.original_annotation.provisional_evidence_spans.find(s=>s.role==='CURRENT_GOAL'),goal=r.proposed_annotation.provisional_evidence_spans.find(s=>s.role==='CURRENT_GOAL');assert(goal.text.length>0);assert(r.proposed_annotation.provisional_evidence_spans.some(s=>s.role!=='CURRENT_GOAL'&&s.role!=='OBJECT')||goal.text.replace(/[。.!?？]+$/u,'')!==old.text.replace(/[。.!?？]+$/u,''));}else assert.deepEqual(r.original_annotation,r.proposed_annotation);
 }
 assert(suffix.some(r=>r.proposed_annotation.provisional_evidence_spans.some(s=>s.role==='NEGATION'&&s.text==='不调用任何模型或在线服务')));assert(suffix.some(r=>r.proposed_annotation.provisional_evidence_spans.some(s=>s.role==='NEGATION'&&s.text==='without accessing real files')));
 assert.equal(result.ordinary_cal_reviewed_rows,54);assert.equal(result.ordinary_cal_unreviewed_rows,378);assert.equal(result.preserved_prefix_records,768);assert.equal(result.source_packet_reads,8);assert.equal(result.new_records,54);assert.equal(result.new_pair_direction_reviews,0);assert.equal(result.preserved_pair_direction_reviews,96);assert.equal(result.pair_label_holds,12);assert.deepEqual(result.safety_pair_reviews,prefix.safety_pair_review_records);assert.equal(result.source_pairs_mutated,0);assert.equal(result.new_source_intake_revisions,0);assert.equal(result.independent_pair_credit,0);assert.equal(result.complete_native_output_parity,'UNTESTED');
 assert.equal(audit.semantic_evaluations,0);assert.equal(audit.independent_reviews,0);assert.equal(audit.calibration_admission,'HOLD_SOURCE_GOLD_MECHANISM_REVIEW_AND_ACCOUNTING');assert.equal(audit.capability_verdict,'UNTESTED');assert.equal(audit.resource_verdict,'NOT_QUALIFIED');
});
