import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {reviewDigest,validateDevelopmentReviewJournal} from './development_review_journal.mjs';
const root=new URL('../../',import.meta.url),read=p=>readFile(new URL(p,root),'utf8'),json=async p=>JSON.parse(await read(p)),sha=s=>createHash('sha256').update(s).digest('hex');
test('516 actual source memberships preserve432 ancestry;24 context directions and8 holds are source review, never Router safety PASS',async()=>{
 const registry=await json('data/zero_model_refoundation/development/development_review_registry_v0.1.json'),prefix=await json('data/zero_model_refoundation/development/development_review_journal_v0.6.json'),journal=await json('data/zero_model_refoundation/development/development_review_journal_v0.7.json'),result=await json('docs/zero-model-refoundation-v1/ZMR-03_DEV_V04_SAFETY_SEED_REVIEW_RESULT.json');
 assert.deepEqual(journal.records.slice(0,432),prefix.records);assert.equal(journal.prefix_journal_sha256,reviewDigest(prefix));assert.equal(journal.prefix_tail_sha256,'2de6631e3ce498dc9d7a71d99c403d0b0933d60e554741e05253450617a38463');
 const catalog=await read('catalog/system_topic_catalog_v0.2.yaml');assert.equal(sha(catalog),registry.catalog_sha256);const topics=[...catalog.matchAll(/^  - topic_id: (.+)$/gm)].map(x=>x[1]);
 const paths=[1,2,3,4,5].map(n=>'data/zero_model_refoundation/development/provisional_tune_v0.4_slice'+n+'.json').concat('data/zero_model_refoundation/development/provisional_safety_v0.4_seed.json'),packets=await Promise.all(paths.map(async path=>({path,utf8:await read(path)}))),rows=packets.flatMap(p=>JSON.parse(p.utf8).rows),seed=JSON.parse(packets[5].utf8);
 const audit=validateDevelopmentReviewJournal({registry,journal,topics,packets});for(const [k,v] of Object.entries(audit))assert.deepEqual(result[k],v,k);
 assert.equal(result.journal_sha256,reviewDigest(journal));assert.equal(result.preserved_prefix_journal_sha256,reviewDigest(prefix));assert.deepEqual(result.source_packet_pins,packets.map(p=>({path:p.path,sha256:sha(p.utf8)})));
 assert.deepEqual(journal.records.map(r=>r.row_id),rows.map(r=>r.row_id));assert.equal(result.reviewed_rows,516);assert.equal(result.unreviewed_registered_rows,684);assert.equal(result.reviewed_topics,new Set(rows.flatMap(r=>r.provisional_gold_topics)).size);assert.equal(result.reviewed_topics,144);
 const languages={};for(const r of rows)languages[r.language]=(languages[r.language]??0)+1;assert.deepEqual(result.reviewed_language_counts,languages);assert.deepEqual(audit.dispositions,{LABEL_IDENTIFIABILITY_HOLD:54,PROPOSE_REVISION:356,RETAIN_PROVISIONAL:106});
 const suffix=journal.records.slice(432),reviews=new Map(suffix.map(r=>[r.row_id,r])),originals=new Map(seed.rows.map(r=>[r.row_id,r])),newDispositions={};for(const r of suffix)newDispositions[r.disposition]=(newDispositions[r.disposition]??0)+1;assert.deepEqual(result.new_dispositions,newDispositions);assert.equal(result.new_records,84);assert.equal(result.preserved_prefix_records,432);assert.equal(result.source_packet_reads,6);
 assert(journal.records.every(r=>r.revision===1&&r.independent===false&&r.qualification_credit===0&&r.proposed_annotation.provisional_gold_topics.join()===r.original_annotation.provisional_gold_topics.join()&&r.boundary_hypotheses.every(t=>topics.includes(t))));
 assert.deepEqual(suffix.filter(r=>r.disposition==='LABEL_IDENTIFIABILITY_HOLD').map(r=>r.row_id),['tune-019','tune-027','tune-028','cal-019','cal-031','cal-032','cal-039','cal-042'].map(x=>'safety-v04-'+x));
 const controls=seed.rows.filter(r=>r.kind==='control');assert.equal(controls.length,24);assert.equal(new Set(controls.map(r=>r.scenario_family)).size,8);assert(controls.every(r=>reviews.get(r.row_id).disposition==='RETAIN_PROVISIONAL'&&r.expected_state==='DEFER'&&r.provisional_gold_topics.length===0));
 assert.equal(suffix.filter(r=>r.proposed_annotation.provisional_evidence_spans.some(s=>s.role==='CONTEXT_REFERENT')).length,10);
 const multi=seed.rows.filter(r=>r.kind==='multi');assert.equal(multi.length,12);assert.equal(multi.filter(r=>reviews.get(r.row_id).disposition==='PROPOSE_REVISION').length,10);for(const r of multi.filter(r=>reviews.get(r.row_id).disposition==='PROPOSE_REVISION'))assert.equal(reviews.get(r.row_id).proposed_annotation.provisional_evidence_spans.filter(s=>s.role==='CURRENT_GOAL').length,2);
 assert.equal(seed.pairs.length,24);assert.deepEqual(result.safety_pair_reviews,journal.safety_pair_review_records);assert.deepEqual(journal.safety_pair_review_records.map(p=>p.pair_id),seed.pairs.map(p=>p.id));
 for(let i=0;i<seed.pairs.length;i++){
  const p=seed.pairs[i],receipt=journal.safety_pair_review_records[i],base=originals.get(p.base_id),variant=originals.get(p.variant_id),br=reviews.get(p.base_id),vr=reviews.get(p.variant_id),{pair_review_sha256,...body}=receipt;
  assert.equal(pair_review_sha256,reviewDigest(body));assert.equal(receipt.original_pair_sha256,reviewDigest(p));assert.equal(receipt.source_packet_sha256,sha(packets[5].utf8));assert.equal(receipt.base_bundle_sha256,base.fingerprints.bundle_sha256);assert.equal(receipt.variant_bundle_sha256,variant.fingerprints.bundle_sha256);assert.equal(receipt.base_review_sha256,br.record_sha256);assert.equal(receipt.variant_review_sha256,vr.record_sha256);
  assert.equal(br.pair_id,p.id);assert.equal(vr.pair_id,p.id);assert.equal(br.pair_role,'BASE');assert.equal(vr.pair_role,'VARIANT');assert.equal(base.current,variant.current);assert.equal(p.split,base.split);assert.equal(base.split,variant.split);assert.equal(base.scenario_family,variant.scenario_family);assert.equal(variant.title,'');assert.deepEqual(variant.recent,[]);assert(base.title||base.recent.length);
  if(p.kind==='context_required'){assert.equal(p.operation,'DELETE_TITLE_AND_ALL_RECENT');assert.equal(base.expected_state,'ASSIGNED');assert.equal(variant.expected_state,'DEFER');assert.deepEqual(variant.provisional_gold_topics,[]);}else{assert.equal(p.operation,'DELETE_MISLEADING_TITLE_AND_RECENT');assert.equal(base.expected_state,variant.expected_state);assert.deepEqual(base.provisional_gold_topics,variant.provisional_gold_topics);}
  assert.equal(receipt.label_review_status,[br,vr].some(r=>r.disposition==='LABEL_IDENTIFIABILITY_HOLD')?'LABEL_IDENTIFIABILITY_HOLD':'PROVISIONAL_EXPECTATION_UNACCEPTED');assert.equal(receipt.native_output_invariance,'UNTESTED_NO_ROUTER_PREDICTIONS');assert.equal(receipt.reviewer_role,'CANDIDATE_WRITER');assert.equal(receipt.independent,false);for(const k of ['qualification_credit','candidate_prediction_exposures','semantic_evaluations'])assert.equal(receipt[k],0);
 }
 assert.equal(result.pair_label_holds,4);assert.equal(result.safety_original_pre_intake_revisions,seed.pre_intake_revision.round);assert.equal(result.safety_original_pre_intake_revisions,1);assert.equal(result.new_source_intake_revisions,0);assert.equal(result.source_pairs_mutated,0);assert.equal(result.independent_pair_credit,0);assert.equal(result.complete_native_output_parity,'UNTESTED');
 assert.equal(audit.semantic_evaluations,0);assert.equal(audit.independent_reviews,0);assert.equal(audit.calibration_admission,'HOLD_SOURCE_GOLD_MECHANISM_REVIEW_AND_ACCOUNTING');assert.equal(audit.capability_verdict,'UNTESTED');assert.equal(audit.resource_verdict,'NOT_QUALIFIED');
});
