import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixExpansion10Review} from './mechanism_matrix_expansion10_review.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function baseSupplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),part6Utf8=await read(dir+'mechanism_matrix_train_part6_v0.1.json'),part6ReviewUtf8=await read(dir+'mechanism_matrix_train_part6_review_v0.1.json'),part7Utf8=await read(dir+'mechanism_matrix_train_part7_v0.1.json'),part7ReviewUtf8=await read(dir+'mechanism_matrix_train_part7_review_v0.1.json'),packetUtf8=await read(dir+'mechanism_matrix_train_part8_v0.1.json'),sourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_part8_review_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 const sourceReviewUtf8=await read(dir+'mechanism_matrix_train_part8_review_v0.1.json');
 const newPacketUtf8=await read(dir+'mechanism_matrix_train_expansion1_v0.1.json'),newPacket=JSON.parse(newPacketUtf8),deficitsUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_SOURCE_DEFICITS_RESULT.json');
 const newSourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'));
 const newSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'),priorReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION1_REVIEW_RESULT.json'),expansionPacketUtf8=await read(dir+'mechanism_matrix_train_expansion2_v0.1.json'),expansionPacket=JSON.parse(expansionPacketUtf8);
 const expansionSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion2_review_v0.1.json'),expansionSourceReview=JSON.parse(expansionSourceReviewUtf8),priorExpansionReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION2_REVIEW_RESULT.json'),intakePacketUtf8=await read(dir+'mechanism_matrix_train_expansion3_v0.1.json'),intakePacket=JSON.parse(intakePacketUtf8);
 const intakeSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion3_review_v0.1.json'),intakeSourceReview=JSON.parse(intakeSourceReviewUtf8),priorThirdReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION3_REVIEW_RESULT.json'),fourthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion4_v0.1.json'),fourthPacket=JSON.parse(fourthPacketUtf8);
 const fourthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion4_review_v0.1.json'),fourthSourceReview=JSON.parse(fourthSourceReviewUtf8),priorFourthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION4_REVIEW_RESULT.json'),fifthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion5_v0.1.json'),fifthPacket=JSON.parse(fifthPacketUtf8);
 const fifthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion5_review_v0.1.json'),fifthSourceReview=JSON.parse(fifthSourceReviewUtf8),priorFifthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION5_REVIEW_RESULT.json'),sixthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion6_v0.1.json'),sixthPacket=JSON.parse(sixthPacketUtf8);
 const sixthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion6_review_v0.1.json'),sixthSourceReview=JSON.parse(sixthSourceReviewUtf8),priorSixthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION6_REVIEW_RESULT.json'),seventhPacketUtf8=await read(dir+'mechanism_matrix_train_expansion7_v0.1.json'),seventhPacket=JSON.parse(seventhPacketUtf8);
 const seventhSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion7_review_v0.1.json'),seventhSourceReview=JSON.parse(seventhSourceReviewUtf8),priorSeventhReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION7_REVIEW_RESULT.json'),eighthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion8_v0.1.json'),eighthPacket=JSON.parse(eighthPacketUtf8);
 return {eighthSourceReview:JSON.parse(await read(dir+'mechanism_matrix_train_expansion8_review_v0.1.json')),eighthPacket,eighthPacketUtf8,seventhSourceReview,seventhSourceReviewUtf8,priorSeventhReviewResultUtf8,seventhPacket,seventhPacketUtf8,sixthSourceReview,sixthSourceReviewUtf8,priorSixthReviewResultUtf8,sixthPacket,sixthPacketUtf8,fifthSourceReview,fifthSourceReviewUtf8,priorFifthReviewResultUtf8,fifthPacket,fifthPacketUtf8,fourthSourceReview,fourthSourceReviewUtf8,priorFourthReviewResultUtf8,fourthPacket,fourthPacketUtf8,intakeSourceReview,intakeSourceReviewUtf8,priorThirdReviewResultUtf8,intakePacket,intakePacketUtf8,expansionSourceReview,expansionSourceReviewUtf8,priorExpansionReviewResultUtf8,expansionPacket,expansionPacketUtf8,newSourceReviewUtf8,priorReviewResultUtf8,newSourceReview,newPacket,newPacketUtf8,deficitsUtf8,sourceReview,sourceReviewUtf8,packet:JSON.parse(packetUtf8),packetUtf8,part7:JSON.parse(part7Utf8),part7Utf8,part7Review:JSON.parse(part7ReviewUtf8),part7ReviewUtf8,part6:JSON.parse(part6Utf8),part6Utf8,part6Review:JSON.parse(part6ReviewUtf8),part6ReviewUtf8,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}



async function sourceSupplied(){
 const base=await baseSupplied(),eighthSourceReviewUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion8_review_v0.1.json'),ninthPacketUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_v0.1.json'),priorEighthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION8_REVIEW_RESULT.json');
 return {...base,eighthSourceReviewUtf8,ninthPacket:JSON.parse(ninthPacketUtf8),ninthPacketUtf8,priorEighthReviewResultUtf8};
}

async function qaSupplied(){return {...await sourceSupplied(),ninthSourceReview:JSON.parse(await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_review_v0.1.json'))};}

async function tenthSupplied(){
 const base=await qaSupplied(),ninthSourceReviewUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_review_v0.1.json'),tenthPacketUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion10_v0.1.json'),priorNinthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION9_REVIEW_RESULT.json');
 return {...base,ninthSourceReviewUtf8,tenthPacket:JSON.parse(tenthPacketUtf8),tenthPacketUtf8,priorNinthReviewResultUtf8};
}

async function supplied(){return {...await tenthSupplied(),tenthSourceReview:JSON.parse(await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion10_review_v0.1.json'))};}

test('actual full144 source10 writer review preserves1152 sources and41labelholds/32roleholds without qualification',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION10_REVIEW_RESULT.json'));
 for(const p of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(p.path)),p.sha256,p.path);
 assert.equal(seedHash(input.tenthPacketUtf8),'48740ee57f80449ea63390d574e3850074548c873538c0b40613df5cb9387cca');
 const a=auditMechanismMatrixExpansion10Review(input);assert.deepEqual(a,receipt.audit);assert.equal(a.new_writer_reviewed_rows,144);assert.deepEqual(a.new_dispositions,{RETAIN_PROVISIONAL_WRITER_ONLY:142,LABEL_IDENTIFIABILITY_HOLD:2});assert.deepEqual(a.new_label_hold_ids,[89,136].map(n=>'ZMR-MATRIX-TRAIN-EXPANSION10-'+String(n).padStart(3,'0')));assert.deepEqual(a.new_role_hold_ids,[17,27,81,91,115,117,127,141].map(n=>'ZMR-MATRIX-TRAIN-EXPANSION10-'+String(n).padStart(3,'0')));assert.equal(a.combined_writer_reviewed_rows,1152);assert.equal(a.combined_label_hold_ids.length,41);assert.equal(a.combined_role_hold_ids.length,32);assert.equal(a.older_roles_without_explicit_disposition,378);assert.equal(a.full_topic_universe,144);assert.equal(a.raw_rows,1152);assert.equal(a.new_neighbor_cards,0);assert.equal(a.new_neighbor_edges,0);assert.equal(a.combined_provisional_neighbor_cards,144);assert.equal(a.combined_provisional_neighbor_edges,432);assert.equal(a.directional_source_cases,0);assert.equal(a.adjudicated_edges,0);assert.equal(a.accepted_role_rows,0);assert.equal(a.accepted_gold_rows,0);assert.equal(a.independent_quota_credit,0);
});
test('rehashed source/gold/role changes and independent,admission,budget,graph claims rejected',async()=>{
 const input=await supplied();for(const [change,error]of [
 [q=>q.source_main='invented',/registered source/],[q=>q.accepted_role_rows=144,/no independent/],[q=>q.accepted_gold_rows=144,/no independent/],[q=>q.independent_reviewers=1,/no independent/],[q=>q.new_stable_allocations=1,/no admission/],[q=>q.compiler_admission='PASS',/no admission/],[q=>q.candidate_predictions=1,/no admission/],[q=>q.capability_verdict='PASS',/qualification/],
 [q=>q.records[0].original_gold_sha256='changed',/original bytes/],[q=>q.records[0].original_spans_sha256='changed',/original bytes/],[q=>q.records[0].original_bundle_sha256='changed',/original bytes/],[q=>q.records[88].proposed_positive_labels=[input.tenthPacket.rows[88].topic_id,...q.records[88].competing_topic_hypotheses],/no silent/],[q=>q.records[75].proposed_role_replacements=[{role:'OBJECT',text:'两项要求'}],/no silent/],[q=>q.records[0].disposition='LABEL_IDENTIFIABILITY_HOLD',/hold explanation/],[q=>q.records[0].independent=true,/writer\/freeze/],[q=>q.records[88].competing_topic_hypotheses=[],/hold explanation/],[q=>q.records[1].role_review_disposition='ACCEPTED',/frozen role/],[q=>q.new_neighbor_edges=144,/graph\/family/],[q=>q.directional_source_cases=144,/graph\/family/],[q=>q.qualified_heldout_family_count=2,/graph\/family/]
 ]){const tenthSourceReview=structuredClone(input.tenthSourceReview);change(tenthSourceReview);tenthSourceReview.records_sha256=seedHash(canonicalJSON(tenthSourceReview.records));assert.throws(()=>auditMechanismMatrixExpansion10Review({...input,tenthSourceReview}),error);}
 assert.throws(()=>auditMechanismMatrixExpansion10Review({...input,tenthPacketUtf8:input.tenthPacketUtf8+' '}),/registered source/);assert.throws(()=>auditMechanismMatrixExpansion10Review({...input,topicIds:input.topicIds.slice(0,18)}),/full144/);
});
test('writer-only review deterministic,pure and cannot mint independent,capability,resource or ceiling evidence',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixExpansion10Review(input),b=auditMechanismMatrixExpansion10Review(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.original_inputs_gold_roles_preserved,true);for(const k of ['source_input_revisions','independent_reviewers','independent_quota_credit','accepted_gold_rows','accepted_role_rows','candidate_predictions','semantic_evaluations','new_stable_allocations'])assert.equal(a[k],0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.qualified_meaningful_families,null);assert.equal(a.qualified_heldout_family_count,null);assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);
});

