import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixExpansion5Review} from './mechanism_matrix_expansion5_review.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function supplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),part6Utf8=await read(dir+'mechanism_matrix_train_part6_v0.1.json'),part6ReviewUtf8=await read(dir+'mechanism_matrix_train_part6_review_v0.1.json'),part7Utf8=await read(dir+'mechanism_matrix_train_part7_v0.1.json'),part7ReviewUtf8=await read(dir+'mechanism_matrix_train_part7_review_v0.1.json'),packetUtf8=await read(dir+'mechanism_matrix_train_part8_v0.1.json'),sourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_part8_review_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 const sourceReviewUtf8=await read(dir+'mechanism_matrix_train_part8_review_v0.1.json');
 const newPacketUtf8=await read(dir+'mechanism_matrix_train_expansion1_v0.1.json'),newPacket=JSON.parse(newPacketUtf8),deficitsUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_SOURCE_DEFICITS_RESULT.json');
 const newSourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'));
 const newSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'),priorReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION1_REVIEW_RESULT.json'),expansionPacketUtf8=await read(dir+'mechanism_matrix_train_expansion2_v0.1.json'),expansionPacket=JSON.parse(expansionPacketUtf8);
 const expansionSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion2_review_v0.1.json'),expansionSourceReview=JSON.parse(expansionSourceReviewUtf8),priorExpansionReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION2_REVIEW_RESULT.json'),intakePacketUtf8=await read(dir+'mechanism_matrix_train_expansion3_v0.1.json'),intakePacket=JSON.parse(intakePacketUtf8);
 const intakeSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion3_review_v0.1.json'),intakeSourceReview=JSON.parse(intakeSourceReviewUtf8),priorThirdReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION3_REVIEW_RESULT.json'),fourthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion4_v0.1.json'),fourthPacket=JSON.parse(fourthPacketUtf8),fourthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion4_review_v0.1.json'),fourthSourceReview=JSON.parse(fourthSourceReviewUtf8),priorFourthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION4_REVIEW_RESULT.json'),fifthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion5_v0.1.json'),fifthPacket=JSON.parse(fifthPacketUtf8),fifthSourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_expansion5_review_v0.1.json'));
 return {fifthSourceReview,fifthPacket,fifthPacketUtf8,fourthSourceReviewUtf8,priorFourthReviewResultUtf8,fourthSourceReview,fourthPacket,fourthPacketUtf8,intakeSourceReviewUtf8,priorThirdReviewResultUtf8,intakeSourceReview,intakePacket,intakePacketUtf8,expansionSourceReview,expansionSourceReviewUtf8,priorExpansionReviewResultUtf8,expansionPacket,expansionPacketUtf8,newSourceReviewUtf8,priorReviewResultUtf8,newSourceReview,newPacket,newPacketUtf8,deficitsUtf8,sourceReview,sourceReviewUtf8,packet:JSON.parse(packetUtf8),packetUtf8,part7:JSON.parse(part7Utf8),part7Utf8,part7Review:JSON.parse(part7ReviewUtf8),part7ReviewUtf8,part6:JSON.parse(part6Utf8),part6Utf8,part6Review:JSON.parse(part6ReviewUtf8),part6ReviewUtf8,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}



test('actual expansion5 source-writer QA preserves702 sources and32label holds/eleven role holds without qualification',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION5_REVIEW_RESULT.json'));
 for(const p of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(p.path)),p.sha256,p.path);
 assert.equal(seedHash(input.fifthPacketUtf8),'03d941a88aac8ee247cda20b66f2dd8b50837b0579c378078eb90380f0167dcd');
 const a=auditMechanismMatrixExpansion5Review(input);assert.deepEqual(a,receipt.audit);assert.equal(a.new_writer_reviewed_rows,54);assert.deepEqual(a.new_dispositions,{RETAIN_PROVISIONAL_WRITER_ONLY:54,LABEL_IDENTIFIABILITY_HOLD:0});assert.deepEqual(a.new_label_hold_ids,[]);assert.deepEqual(a.new_role_hold_ids,['ZMR-MATRIX-TRAIN-EXPANSION5-010']);assert.equal(a.combined_writer_reviewed_rows,702);assert.equal(a.combined_label_hold_ids.length,32);assert.deepEqual(a.combined_role_hold_ids,['ZMR-MATRIX-TRAIN-PART8-026','ZMR-MATRIX-TRAIN-EXPANSION1-049','ZMR-MATRIX-TRAIN-EXPANSION3-034','ZMR-MATRIX-TRAIN-EXPANSION3-049','ZMR-MATRIX-TRAIN-EXPANSION3-050','ZMR-MATRIX-TRAIN-EXPANSION4-012','ZMR-MATRIX-TRAIN-EXPANSION4-024','ZMR-MATRIX-TRAIN-EXPANSION4-030','ZMR-MATRIX-TRAIN-EXPANSION4-036','ZMR-MATRIX-TRAIN-EXPANSION4-054','ZMR-MATRIX-TRAIN-EXPANSION5-010']);assert.equal(a.older_roles_without_explicit_disposition,378);assert.equal(a.full_topic_universe,144);assert.equal(a.new_neighbor_cards,0);assert.equal(a.new_neighbor_edges,0);assert.equal(a.combined_provisional_neighbor_cards,144);assert.equal(a.combined_provisional_neighbor_edges,432);assert.equal(a.directional_source_cases,0);assert.equal(a.adjudicated_edges,0);assert.equal(a.accepted_role_rows,0);assert.equal(a.accepted_gold_rows,0);assert.equal(a.independent_quota_credit,0);
});
test('rehashed source/gold/role changes,independence,admission,budget and graph/family qualification rejected',async()=>{
 const input=await supplied();for(const [change,error]of [
 [q=>q.source_main='invented',/registered source/],[q=>q.accepted_role_rows=54,/no independent/],[q=>q.accepted_gold_rows=54,/no independent/],[q=>q.independent_reviewers=1,/no independent/],[q=>q.new_stable_allocations=1,/no admission/],[q=>q.compiler_admission='PASS',/no admission/],[q=>q.candidate_predictions=1,/no admission/],[q=>q.capability_verdict='PASS',/qualification/],
 [q=>q.records[0].original_gold_sha256='changed',/original bytes/],[q=>q.records[0].original_spans_sha256='changed',/original bytes/],[q=>q.records[0].original_bundle_sha256='changed',/original bytes/],[q=>q.records[26].proposed_positive_labels=[input.fifthPacket.rows[17].topic_id,...q.records[26].competing_topic_hypotheses],/no silent/],[q=>q.records[48].proposed_role_replacements=[{role:'OBJECT',text:'两项讨论'}],/no silent/],[q=>q.records[26].disposition='LABEL_IDENTIFIABILITY_HOLD',/hold explanation/],[q=>q.records[0].independent=true,/writer\/freeze/],[q=>q.new_neighbor_edges=54,/graph\/family/],[q=>q.directional_source_cases=54,/graph\/family/],[q=>q.qualified_heldout_family_count=2,/graph\/family/]
 ]){const fifthSourceReview=structuredClone(input.fifthSourceReview);change(fifthSourceReview);fifthSourceReview.records_sha256=seedHash(canonicalJSON(fifthSourceReview.records));assert.throws(()=>auditMechanismMatrixExpansion5Review({...input,fifthSourceReview}),error);}
 assert.throws(()=>auditMechanismMatrixExpansion5Review({...input,fifthPacketUtf8:input.fifthPacketUtf8+' '}),/registered source/);assert.throws(()=>auditMechanismMatrixExpansion5Review({...input,topicIds:input.topicIds.slice(0,18)}),/full144/);
});
test('source-only writer review is deterministic,pure and cannot mint independent/capability/resource evidence',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixExpansion5Review(input),b=auditMechanismMatrixExpansion5Review(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.original_inputs_gold_roles_preserved,true);for(const k of ['source_input_revisions','independent_reviewers','independent_quota_credit','accepted_gold_rows','accepted_role_rows','candidate_predictions','semantic_evaluations','new_stable_allocations'])assert.equal(a[k],0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.qualified_meaningful_families,null);assert.equal(a.qualified_heldout_family_count,null);assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);
});
