/** Supply-only original-source batch audit;no candidate,compiler,network or discovery. */
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixPart4Review} from './mechanism_matrix_part4_review.mjs';
const must=(v,m)=>{if(!v)throw Error(m);};
const norm=s=>s.normalize('NFKC').toLowerCase().replace(/\s+/gu,' ').trim();
const grams=s=>{const c=Array.from(norm(s));return new Set(c.length<3?[c.join('')]:c.slice(0,-2).map((_,i)=>c.slice(i,i+3).join('')));};
const dice=(a,b)=>{let n=0;for(const g of a)if(b.has(g))n++;return 2*n/(a.size+b.size||1);};
export function auditMechanismMatrixTrainPart5({packet,part4,part4Utf8,part4Review,part4ReviewUtf8,part3,part3Utf8,part3Review,part3ReviewUtf8,prior,priorUtf8,qa,qaUtf8,seed,seedUtf8,review,reviewUtf8,plan,planUtf8,topicIds}){
 const base=auditMechanismMatrixPart4Review({sourceReview:part4Review,packet:part4,packetUtf8:part4Utf8,part3,part3Utf8,part3Review,part3ReviewUtf8,prior,priorUtf8,qa,qaUtf8,seed,seedUtf8,review,reviewUtf8,plan,planUtf8,topicIds});
 must(packet.baseline_part4_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part4_v0.1.json'&&packet.baseline_part4_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part4_review_v0.1.json'&&packet.baseline_part4_sha256===seedHash(part4Utf8)&&packet.baseline_part4_review_sha256===seedHash(part4ReviewUtf8),'part5 prior source/QA identity');
 must(packet.baseline_part3_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part3_v0.1.json'&&packet.baseline_part3_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part3_review_v0.1.json'&&packet.baseline_part3_sha256===seedHash(part3Utf8)&&packet.baseline_part3_review_sha256===seedHash(part3ReviewUtf8),'part4 prior source/QA identity');
 must(packet.baseline_part2_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part2_v0.1.json'&&packet.baseline_part2_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_part2_review_v0.1.json'&&packet.baseline_part2_sha256===seedHash(priorUtf8)&&packet.baseline_part2_review_sha256===seedHash(qaUtf8),'part4 registered part2 source/QA identity');
 for(const [obj,bytes]of [[part4,part4Utf8],[part4Review,part4ReviewUtf8],[part3,part3Utf8],[part3Review,part3ReviewUtf8],[prior,priorUtf8],[qa,qaUtf8],[seed,seedUtf8],[review,reviewUtf8],[plan,planUtf8]])must(canonicalJSON(obj)===canonicalJSON(JSON.parse(bytes)),'part5 supplied object/bytes mismatch');
 must(packet?.schema==='ZMR-MECHANISM-MATRIX-DRAFT-BATCH-1'&&packet.evidence_class==='NON_INDEPENDENT_DEVELOPMENT_EVIDENCE','batch evidence');
 must(packet.plan_path==='data/zero_model_refoundation/development/development_mechanism_matrix_plan_v0.1.json'&&packet.baseline_seed_path==='data/zero_model_refoundation/development/mechanism_matrix_train_seed_v0.1.json'&&packet.baseline_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_seed_review_v0.1.json','batch source paths not registered');
 must(packet.plan_sha256===seedHash(planUtf8)&&packet.catalog_sha256===plan.catalog_sha256&&packet.baseline_seed_sha256===seedHash(seedUtf8)&&packet.baseline_review_sha256===seedHash(reviewUtf8),'batch source identity');
 must(packet.registration_main==='5e3d133ff2481a531291d2bf4415e24a03f14578'&&packet.registration_tree==='e7e08bc5e529361892e367374593cdf6aff1da31','batch canonical registration');
 must(packet.status==='SOURCE_BYTES_FROZEN_DRAFT_UNACCEPTED_NO_COMPILER_ADMISSION'&&packet.source_license==='ORIGINAL_CANDIDATE_WRITER_FICTIONAL_DECLARATION_NOT_INDEPENDENTLY_VERIFIED'&&packet.source_topic_position_per_domain===4,'batch source admission/selection');
 must(packet.writer_id==='candidate-writer'&&packet.writer_cohort==='candidate-writer-G0'&&packet.source_family==='candidate-writer-G0'&&packet.generation_claim==='NONE_NO_STABLE_ALLOCATION_OR_BUDGET_RESET','batch writer/generation lineage');
 for(const k of ['independent_quota_credit','accepted_rows','candidate_prediction_exposures','semantic_evaluations','new_competition_generations','source_intake_revision'])must(packet[k]===0,'batch cannot mint qualification/evaluation/allowance');
 must(packet.data_qualification==='NOT_QUALIFIED'&&packet.capability_verdict==='UNTESTED'&&packet.resource_verdict==='NOT_QUALIFIED'&&packet.sealed_contents_created===false&&packet.saturation_ceiling_claim===false,'batch qualification claim');
 must(packet.near_duplicate_screen.threshold===.55&&packet.near_duplicate_screen.scope==='NEW54_PLUS_REGISTERED_SEED54_PART2_54_PART3_54_PART4_54_ONLY'&&packet.near_duplicate_screen.independent_review===false,'batch screen scope/threshold');
 must(packet.rows.length===54&&packet.rows_sha256===seedHash(canonicalJSON(packet.rows)),'batch source count/digest');
 const selected=plan.cards.filter((c,i)=>i%8===4);must(selected.length===18&&new Set(selected.map(c=>c.domain)).size===18,'Catalog fifth Topic scope');
 const priorRows=[...seed.rows,...prior.rows,...part3.rows,...part4.rows],rows=[...priorRows,...packet.rows],currentHashes=new Set(priorRows.map(r=>r.normalized_current_sha256)),bundleHashes=new Set(priorRows.map(r=>r.bundle_sha256)),lang={zh:0,en:0,mixed:0},literalIds=[];
 for(const [i,r]of packet.rows.entries()){
  const language=['zh','en','mixed'][i%3],card=selected[Math.floor(i/3)],allocation=card.train_allocations[[0,1,4][i%3]];
  must(r.id===`ZMR-MATRIX-TRAIN-PART5-${String(i+1).padStart(3,'0')}`&&r.topic_id===card.topic_id&&r.language===language&&r.split==='TRAIN'&&r.mechanism_family===allocation.mechanism_family&&allocation.languages[language]>0,'batch row/nominal allocation');
  must(r.writer_id==='candidate-writer'&&r.writer_cohort==='candidate-writer-G0'&&r.source_family==='candidate-writer-G0'&&r.source_id===r.id+'-original'&&r.scenario_id===r.id+'-scenario','batch source provenance');
  must(r.lineage.writer==='candidate-writer-G0'&&r.lineage.source===r.source_id&&r.lineage.scenario===r.scenario_id&&r.lineage.shared_authoring_run===packet.batch_id&&r.lineage.template_review==='UNREVIEWED_POSSIBLE_SHARED_SKELETONS'&&r.lineage.translation_family===null&&r.lineage.paraphrase_family===null&&r.lineage.contrast_family===null,'batch lineage incomplete');
  must(r.source_status==='ORIGINAL_FICTIONAL_WRITER_DRAFT_NOT_INDEPENDENT_SOURCE'&&r.label_status==='PROVISIONAL_WRITER_LABEL_UNACCEPTED'&&r.reviewer_id==='candidate-writer'&&r.independent_reviewer_count===0&&r.independent_quota_credit===0,'batch cannot simulate independent gold');
  must(r.provisional_gold.expected_state==='ASSIGNED'&&canonicalJSON(r.provisional_gold.topics)===canonicalJSON([card.topic_id])&&canonicalJSON(r.provisional_gold.excluded_topics)==='[]'&&r.identifiability==='PENDING_BOUNDARY_AND_INDEPENDENT_ADJUDICATION'&&r.writer_rationale.length>=30,'batch provisional labels/holds');
  const input=r.input;must(input&&Object.keys(input).sort().join(',')==='current,recent,title'&&typeof input.current==='string'&&input.current.length>=20&&typeof input.title==='string'&&Array.isArray(input.recent)&&input.recent.every(t=>typeof t==='string'),'batch product bundle');
  must(r.input_sha256===seedHash(input.current)&&r.normalized_current_sha256===seedHash(norm(input.current))&&r.bundle_sha256===seedHash(canonicalJSON(input)),'batch input fingerprints');
  must(!currentHashes.has(r.normalized_current_sha256)&&!bundleHashes.has(r.bundle_sha256),'unexplained new/registered duplicate');currentHashes.add(r.normalized_current_sha256);bundleHashes.add(r.bundle_sha256);
  for(const role of ['ACTION','OBJECT','QUALIFIER'])must(r.spans.some(s=>s.role===role),'batch missing role');
  if(r.mechanism_family==='mf-context-continuation')must(input.recent.length>0&&r.spans.some(s=>s.role==='ANTECEDENT'&&s.field.startsWith('recent.')),'batch continuation antecedent');
  for(const s of r.spans){const t=s.field==='current'?input.current:s.field==='title'?input.title:/^recent\.[0-9]+$/.test(s.field)?input.recent[Number(s.field.slice(7))]:undefined;must(typeof t==='string'&&['ACTION','OBJECT','QUALIFIER','ANTECEDENT'].includes(s.role)&&Number.isSafeInteger(s.start)&&Number.isSafeInteger(s.end)&&s.start>=0&&s.end>s.start&&s.end<=t.length&&t.slice(s.start,s.end)===s.text,'batch exact UTF16 span');for(const n of [s.start,s.end])must(n===0||n===t.length||!(t.charCodeAt(n-1)>=0xd800&&t.charCodeAt(n-1)<=0xdbff&&t.charCodeAt(n)>=0xdc00&&t.charCodeAt(n)<=0xdfff),'batch surrogate boundary');}
  must(canonicalJSON(r.factors)===canonicalJSON(Object.fromEntries(['ACTION','OBJECT','QUALIFIER'].map(role=>[role.toLowerCase(),r.spans.find(s=>s.role===role).text]))),'batch factor/span mismatch');
  must(r.frozen_at===packet.frozen_at&&Number.isFinite(Date.parse(r.frozen_at)),'batch freeze provenance');
  if([card.name_zh,card.name_en].some(n=>norm(input.current).includes(norm(n))))literalIds.push(r.id);lang[language]++;
 }
 const matrix={},combinedLang={zh:0,en:0,mixed:0};for(const r of rows){matrix[r.mechanism_family]??={zh:0,en:0,mixed:0};matrix[r.mechanism_family][r.language]++;combinedLang[r.language]++;}
 const flags=[],g=rows.map(r=>grams(r.input.current));for(let i=0;i<rows.length;i++)for(let j=Math.max(i+1,216);j<rows.length;j++){const score=dice(g[i],g[j]);if(score>=.55)flags.push({first:rows[i].id,second:rows[j].id,dice:score,disposition:'HOLD_WRITER_SCREEN_NOT_INDEPENDENTLY_REVIEWED'});}
 const topics=new Set(rows.map(r=>r.topic_id));
 return {schema:'ZMR-MECHANISM-MATRIX-TRAIN-PART5-AUDIT-1',evidence_class:packet.evidence_class,new_rows:54,new_topics:18,new_language_counts:lang,combined_source_rows:270,combined_source_topics:topics.size,combined_language_counts:combinedLang,full_topic_universe:144,missing_topics:topicIds.filter(t=>!topics.has(t)),remaining_raw_train_rows:3456-270,remaining_raw_language_rows:{zh:1728-combinedLang.zh,en:1152-combinedLang.en,mixed:576-combinedLang.mixed},combined_nominal_family_language_matrix:matrix,qualified_heldout_family_count:null,semantic_family_equivalence:'UNADJUDICATED_POSSIBLE_OVERLAP',prior_reviewed_rows:base.combined_writer_reviewed_rows,prior_label_holds:base.combined_label_holds,new_source_writer_qa:'PENDING',accepted_rows:0,independent_quota_credit:0,writer_lineage_components:1,independent_scenario_count:null,new_continuation_source_rows:packet.rows.filter(r=>r.mechanism_family==='mf-context-continuation').length,own_literal_name_proxy:{rows:literalIds.length,ids:literalIds,adjudicated_echo_fraction:null},new_and_registered_near_duplicate_flags:flags,screen_scope:packet.near_duplicate_screen.scope,old_v04_or_sealed_overlap_review:'NOT_PERFORMED_NO_OLD_OR_SEALED_READS',source_license:'DECLARATION_ONLY_NOT_INDEPENDENTLY_VERIFIED',candidate_predictions:0,semantic_evaluations:0,new_competition_generations:0,remaining_stable_allowance:null,data_qualification:'NOT_QUALIFIED',capability_verdict:'UNTESTED',resource_verdict:'NOT_QUALIFIED',saturation_ceiling_claim:false};
}
