/** Pure source-only audit of the full144 registered remaining-cell continuation. */
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixExpansion8Review} from './mechanism_matrix_expansion8_review.mjs';
const must=(v,m)=>{if(!v)throw Error(m);};
const norm=s=>s.normalize('NFKC').toLowerCase().replace(/\s+/gu,' ').trim();
const grams=s=>{const c=Array.from(norm(s));return new Set(c.length<3?[c.join('')]:c.slice(0,-2).map((_,i)=>c.slice(i,i+3).join('')));};
const dice=(a,b)=>{let n=0;for(const g of a)if(b.has(g))n++;return 2*n/(a.size+b.size||1);};
export function auditMechanismMatrixTrainExpansion9(input){
 const {ninthPacket:p,ninthPacketUtf8,priorEighthReviewResultUtf8,plan,topicIds}=input,base=auditMechanismMatrixExpansion8Review(input);
 must(canonicalJSON(JSON.parse(ninthPacketUtf8))===canonicalJSON(p),'expansion supplied object/bytes');
 must(canonicalJSON(input.eighthSourceReview)===canonicalJSON(JSON.parse(input.eighthSourceReviewUtf8))&&seedHash(input.eighthSourceReviewUtf8)==='bd19ad23e69cafff97e4ebab23dcd6c469381bddf7a4e523a32581cc592a31c0','expansion registered prior writer QA bytes');
 const receipt=JSON.parse(priorEighthReviewResultUtf8);must(canonicalJSON(receipt.audit)===canonicalJSON(base)&&receipt.source_main==='6113e3de19875fd0af2f53a53060d085cff55668'&&receipt.source_tree==='449d4cf82109c4206d4e81dddf9d5f5d4e79fb5c','expansion registered deficit audit');
 must(p.schema==='ZMR-MECHANISM-MATRIX-QUOTA-EXPANSION-1'&&p.evidence_class==='NON_INDEPENDENT_DEVELOPMENT_EVIDENCE'&&p.status==='SOURCE_BYTES_FROZEN_DRAFT_UNACCEPTED_NO_COMPILER_ADMISSION','expansion source evidence');
 must(p.registration_main==='33e206b08945afb3ace5689a639fae3ed5099c21'&&p.registration_tree==='06700b64159e6d0af7944b26d1ef10d15af022f7'&&p.plan_sha256===seedHash(input.planUtf8)&&p.catalog_sha256===plan.catalog_sha256&&p.baseline_expansion8_sha256===seedHash(input.eighthPacketUtf8)&&p.baseline_expansion8_review_sha256===seedHash(input.eighthSourceReviewUtf8)&&p.baseline_prior_review_result_sha256===seedHash(priorEighthReviewResultUtf8),'expansion registered provenance');
 must(p.plan_path==='data/zero_model_refoundation/development/development_mechanism_matrix_plan_v0.1.json'&&p.baseline_expansion8_path==='data/zero_model_refoundation/development/mechanism_matrix_train_expansion8_v0.1.json'&&p.baseline_expansion8_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_expansion8_review_v0.1.json'&&p.baseline_prior_review_result_path==='docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION8_REVIEW_RESULT.json','expansion registered paths');
 must(p.selection_basis==='EACH_FULL144_CARD_FIRST_REGISTERED_REMAINING_FAMILY_LANGUAGE_CELL_NOT_ERRORS'&&p.generation_claim==='NONE_NO_STABLE_ALLOCATION_OR_BUDGET_RESET'&&p.source_license==='ORIGINAL_CANDIDATE_WRITER_FICTIONAL_DECLARATION_NOT_INDEPENDENTLY_VERIFIED','expansion selection/license/generation');
 for(const k of ['independent_quota_credit','accepted_rows','candidate_prediction_exposures','semantic_evaluations','new_competition_generations','source_intake_revision'])must(p[k]===0,'expansion cannot mint qualification/evaluation/allowance');
 must(p.writer_id==='candidate-writer'&&p.writer_cohort==='candidate-writer-G0'&&p.source_family==='candidate-writer-G0'&&p.data_qualification==='NOT_QUALIFIED'&&p.capability_verdict==='UNTESTED'&&p.resource_verdict==='NOT_QUALIFIED'&&p.sealed_contents_created===false&&p.saturation_ceiling_claim===false,'expansion cannot simulate independence/qualification');
 must(plan.cards.length===144&&topicIds.length===144&&new Set(topicIds).size===144,'expansion full144');
 must(p.rows.length===144&&p.rows_sha256===seedHash(canonicalJSON(p.rows))&&Number.isFinite(Date.parse(p.frozen_at)),'expansion source freeze/count');
 must(p.near_duplicate_screen.threshold===.55&&p.near_duplicate_screen.scope==='NEW144_PLUS_REGISTERED_MATRIX864_ONLY'&&p.near_duplicate_screen.independent_review===false,'expansion screen scope');
 const priorRows=[input.seed,input.prior,input.part3,input.part4,input.part5,input.part6,input.part7,input.packet].flatMap(x=>x.rows).concat(input.newPacket.rows,input.expansionPacket.rows,input.intakePacket.rows,input.fourthPacket.rows,input.fifthPacket.rows,input.sixthPacket.rows,input.seventhPacket.rows,input.eighthPacket.rows);
 must(priorRows.length===864,'expansion prior source count');
 const counts=new Map(),key=(t,f,l)=>t+'\0'+f+'\0'+l;for(const r of priorRows){const k=key(r.topic_id,r.mechanism_family,r.language);counts.set(k,(counts.get(k)||0)+1);}
 const selected=plan.cards.map(card=>{for(const allocation of card.train_allocations)for(const language of ['zh','en','mixed']){const actual=counts.get(key(card.topic_id,allocation.mechanism_family,language))||0;must(actual<=allocation.languages[language],'expansion prior exceeds registered allocation');if(actual<allocation.languages[language])return {card,language,family:allocation.mechanism_family};}throw Error('expansion no registered missing cell');});
 const hashes=new Set(priorRows.map(r=>r.normalized_current_sha256)),bundles=new Set(priorRows.map(r=>r.bundle_sha256)),literalIds=[],lang={zh:0,en:0,mixed:0};
 for(const [i,r]of p.rows.entries()){
  const {card,language,family}=selected[i];must(r.id===`ZMR-MATRIX-TRAIN-EXPANSION9-${String(i+1).padStart(3,'0')}`&&r.topic_id===card.topic_id&&r.language===language&&r.mechanism_family===family&&r.split==='TRAIN','expansion fixed remaining cell');
  must(r.writer_id==='candidate-writer'&&r.writer_cohort==='candidate-writer-G0'&&r.source_family==='candidate-writer-G0'&&r.source_id===r.id+'-original'&&r.scenario_id===r.id+'-scenario'&&r.lineage.writer==='candidate-writer-G0'&&r.lineage.source===r.source_id&&r.lineage.scenario===r.scenario_id&&r.lineage.shared_authoring_run===p.batch_id&&r.lineage.template_review==='UNREVIEWED_POSSIBLE_SHARED_SKELETONS'&&r.lineage.translation_family===null&&r.lineage.paraphrase_family===null&&r.lineage.contrast_family===null,'expansion writer/source lineage');
  must(r.source_status==='ORIGINAL_FICTIONAL_WRITER_DRAFT_NOT_INDEPENDENT_SOURCE'&&r.label_status==='PROVISIONAL_WRITER_LABEL_UNACCEPTED'&&r.reviewer_id==='candidate-writer'&&r.independent_reviewer_count===0&&r.independent_quota_credit===0,'expansion no independent gold');
  must(r.provisional_gold.expected_state==='ASSIGNED'&&canonicalJSON(r.provisional_gold.topics)===canonicalJSON([card.topic_id])&&canonicalJSON(r.provisional_gold.excluded_topics)==='[]'&&r.identifiability==='PENDING_BOUNDARY_AND_INDEPENDENT_ADJUDICATION'&&r.writer_rationale.length>=30,'expansion provisional positive only');
  const b=r.input;must(Object.keys(b).sort().join(',')==='current,recent,title'&&typeof b.current==='string'&&b.current.length>=20&&typeof b.title==='string'&&Array.isArray(b.recent)&&b.recent.every(x=>typeof x==='string'),'expansion source bundle');
  must(r.input_sha256===seedHash(b.current)&&r.normalized_current_sha256===seedHash(norm(b.current))&&r.bundle_sha256===seedHash(canonicalJSON(b)),'expansion source fingerprints');must(!hashes.has(r.normalized_current_sha256)&&!bundles.has(r.bundle_sha256),'expansion unexplained duplicate');hashes.add(r.normalized_current_sha256);bundles.add(r.bundle_sha256);
  for(const role of ['ACTION','OBJECT','QUALIFIER'])must(r.spans.some(s=>s.role===role),'expansion missing role');
  if(family==='mf-context-continuation')must(b.recent.length>0&&r.spans.some(s=>s.role==='ANTECEDENT'&&s.field.startsWith('recent.')),'expansion context antecedent');
  for(const s of r.spans){const t=s.field==='current'?b.current:s.field==='title'?b.title:/^recent\.[0-9]+$/.test(s.field)?b.recent[Number(s.field.slice(7))]:undefined;must(typeof t==='string'&&['ACTION','OBJECT','QUALIFIER','ANTECEDENT'].includes(s.role)&&Number.isSafeInteger(s.start)&&Number.isSafeInteger(s.end)&&s.start>=0&&s.end>s.start&&s.end<=t.length&&t.slice(s.start,s.end)===s.text,'expansion exact UTF16 role');for(const n of [s.start,s.end])must(n===0||n===t.length||!(t.charCodeAt(n-1)>=0xd800&&t.charCodeAt(n-1)<=0xdbff&&t.charCodeAt(n)>=0xdc00&&t.charCodeAt(n)<=0xdfff),'expansion surrogate boundary');}
  must(canonicalJSON(r.factors)===canonicalJSON(Object.fromEntries(['ACTION','OBJECT','QUALIFIER'].map(role=>[role.toLowerCase(),r.spans.find(s=>s.role===role).text])))&&r.frozen_at===p.frozen_at,'expansion factor/span/freeze');
  const k=key(r.topic_id,family,language);counts.set(k,(counts.get(k)||0)+1);if([card.name_zh,card.name_en].some(n=>norm(b.current).includes(norm(n))))literalIds.push(r.id);lang[language]++;
 }
 let remaining=0;const remainingLanguage={zh:0,en:0,mixed:0};for(const card of plan.cards)for(const a of card.train_allocations)for(const l of ['zh','en','mixed']){const missing=a.languages[l]-(counts.get(key(card.topic_id,a.mechanism_family,l))||0);must(missing>=0,'expansion exceeds registered allocation');remaining+=missing;remainingLanguage[l]+=missing;}
 const all=[...priorRows,...p.rows],g=all.map(r=>grams(r.input.current)),flags=[];for(let i=0;i<all.length;i++)for(let j=Math.max(i+1,864);j<all.length;j++){const score=dice(g[i],g[j]);if(score>=.55)flags.push({first:all[i].id,second:all[j].id,dice:score,disposition:'HOLD_WRITER_SCREEN_NOT_INDEPENDENTLY_REVIEWED'});}
 return {schema:'ZMR-MECHANISM-MATRIX-TRAIN-EXPANSION9-AUDIT-1',evidence_class:p.evidence_class,new_rows:144,new_language_counts:lang,new_topics:0,expanded_topics:144,full_topic_universe:144,combined_raw_topics:144,combined_raw_rows:all.length,combined_raw_languages:{zh:432+lang.zh,en:288+lang.en,mixed:144+lang.mixed},remaining_raw_train_rows:remaining,remaining_raw_language_rows:remainingLanguage,prior_writer_reviewed_rows:base.combined_writer_reviewed_rows,prior_label_holds:base.combined_label_hold_ids,prior_role_holds:base.combined_role_hold_ids,new_source_writer_qa:'PENDING',accepted_rows:0,accepted_gold_rows:0,independent_quota_credit:0,new_continuation_source_rows:p.rows.filter(r=>r.input.recent.length>0).length,own_literal_name_proxy:{rows:literalIds.length,ids:literalIds,adjudicated_echo_fraction:null},new_and_registered_near_duplicate_flags:flags,screen_scope:p.near_duplicate_screen.scope,original_prior_sources_gold_roles_preserved:true,writer_lineage_components:1,independent_scenario_count:null,qualified_meaningful_families:null,qualified_heldout_families:null,source_license:'DECLARATION_ONLY_NOT_INDEPENDENTLY_VERIFIED',old_v04_or_sealed_overlap_review:'NOT_PERFORMED_NO_OLD_OR_SEALED_CONTENT_READS',candidate_predictions:0,semantic_evaluations:0,new_competition_generations:0,remaining_stable_allowance:null,data_qualification:'NOT_QUALIFIED',capability_verdict:'UNTESTED',resource_verdict:'NOT_QUALIFIED',saturation_ceiling_claim:false};
}
