import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixTrainExpansion10} from './mechanism_matrix_train_expansion10.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function baseSupplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),part6Utf8=await read(dir+'mechanism_matrix_train_part6_v0.1.json'),part6ReviewUtf8=await read(dir+'mechanism_matrix_train_part6_review_v0.1.json'),part7Utf8=await read(dir+'mechanism_matrix_train_part7_v0.1.json'),part7ReviewUtf8=await read(dir+'mechanism_matrix_train_part7_review_v0.1.json'),packetUtf8=await read(dir+'mechanism_matrix_train_part8_v0.1.json'),sourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_part8_review_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 const sourceReviewUtf8=await read(dir+'mechanism_matrix_train_part8_review_v0.1.json');
 const newPacketUtf8=await read(dir+'mechanism_matrix_train_expansion1_v0.1.json'),newPacket=JSON.parse(newPacketUtf8),deficitsUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_SOURCE_DEFICITS_RESULT.json');
 const newSourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'));
 const newSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'),priorReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION1_REVIEW_RESULT.json'),expansionPacketUtf8=await read(dir+'mechanism_matrix_train_expansion2_v0.1.json'),expansionPacket=JSON.parse(expansionPacketUtf8);
 const expansionSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion2_review_v0.1.json'),expansionSourceReview=JSON.parse(expansionSourceReviewUtf8),priorExpansionReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION2_REVIEW_RESULT.json'),intakePacketUtf8=await read(dir+'mechanism_matrix_train_expansion3_v0.1.json'),intakePacket=JSON.parse(intakePacketUtf8);
 const intakeSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion3_review_v0.1.json'),intakeSourceReview=JSON.parse(intakeSourceReviewUtf8),priorThirdReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION3_REVIEW_RESULT.json'),fourthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion4_v0.1.json'),fourthPacket=JSON.parse(fourthPacketUtf8);
 const fourthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion4_review_v0.1.json'),fourthSourceReview=JSON.parse(fourthSourceReviewUtf8),priorFourthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION4_REVIEW_RESULT.json'),fifthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion5_v0.1.json'),fifthPacket=JSON.parse(fifthPacketUtf8);
 const fifthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion5_review_v0.1.json'),fifthSourceReview=JSON.parse(fifthSourceReviewUtf8),priorFifthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION5_REVIEW_RESULT.json'),sixthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion6_v0.1.json'),sixthPacket=JSON.parse(sixthPacketUtf8);
 const sixthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion6_review_v0.1.json'),sixthSourceReview=JSON.parse(sixthSourceReviewUtf8),priorSixthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION6_REVIEW_RESULT.json'),seventhPacketUtf8=await read(dir+'mechanism_matrix_train_expansion7_v0.1.json'),seventhPacket=JSON.parse(seventhPacketUtf8);
 const seventhSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion7_review_v0.1.json'),seventhSourceReview=JSON.parse(seventhSourceReviewUtf8),priorSeventhReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION7_REVIEW_RESULT.json'),eighthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion8_v0.1.json'),eighthPacket=JSON.parse(eighthPacketUtf8);
 return {eighthSourceReview:JSON.parse(await read(dir+'mechanism_matrix_train_expansion8_review_v0.1.json')),eighthPacket,eighthPacketUtf8,seventhSourceReview,seventhSourceReviewUtf8,priorSeventhReviewResultUtf8,seventhPacket,seventhPacketUtf8,sixthSourceReview,sixthSourceReviewUtf8,priorSixthReviewResultUtf8,sixthPacket,sixthPacketUtf8,fifthSourceReview,fifthSourceReviewUtf8,priorFifthReviewResultUtf8,fifthPacket,fifthPacketUtf8,fourthSourceReview,fourthSourceReviewUtf8,priorFourthReviewResultUtf8,fourthPacket,fourthPacketUtf8,intakeSourceReview,intakeSourceReviewUtf8,priorThirdReviewResultUtf8,intakePacket,intakePacketUtf8,expansionSourceReview,expansionSourceReviewUtf8,priorExpansionReviewResultUtf8,expansionPacket,expansionPacketUtf8,newSourceReviewUtf8,priorReviewResultUtf8,newSourceReview,newPacket,newPacketUtf8,deficitsUtf8,sourceReview,sourceReviewUtf8,packet:JSON.parse(packetUtf8),packetUtf8,part7:JSON.parse(part7Utf8),part7Utf8,part7Review:JSON.parse(part7ReviewUtf8),part7ReviewUtf8,part6:JSON.parse(part6Utf8),part6Utf8,part6Review:JSON.parse(part6ReviewUtf8),part6ReviewUtf8,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}



async function sourceSupplied(){
 const base=await baseSupplied(),eighthSourceReviewUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion8_review_v0.1.json'),ninthPacketUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_v0.1.json'),priorEighthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION8_REVIEW_RESULT.json');
 return {...base,eighthSourceReviewUtf8,ninthPacket:JSON.parse(ninthPacketUtf8),ninthPacketUtf8,priorEighthReviewResultUtf8};
}

async function qaSupplied(){return {...await sourceSupplied(),ninthSourceReview:JSON.parse(await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_review_v0.1.json'))};}

async function supplied(){
 const base=await qaSupplied(),ninthSourceReviewUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion9_review_v0.1.json'),tenthPacketUtf8=await read('data/zero_model_refoundation/development/mechanism_matrix_train_expansion10_v0.1.json'),priorNinthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION9_REVIEW_RESULT.json');
 return {...base,ninthSourceReviewUtf8,tenthPacket:JSON.parse(tenthPacketUtf8),tenthPacketUtf8,priorNinthReviewResultUtf8};
}

test('actual full144 remaining-cell intake preserves all prior pins and holds without qualified quota',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION10_RESULT.json'));
 for(const pin of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(pin.path)),pin.sha256,pin.path);
 const a=auditMechanismMatrixTrainExpansion10(input);assert.deepEqual(a,receipt.audit);assert.equal(a.new_rows,144);assert.equal(a.expanded_topics,144);assert.equal(a.full_topic_universe,144);assert.equal(a.combined_raw_topics,144);assert.equal(a.combined_raw_rows,1152);assert.deepEqual(a.new_language_counts,{zh:144,en:0,mixed:0});assert.deepEqual(a.combined_raw_languages,{zh:720,en:288,mixed:144});assert.equal(a.remaining_raw_train_rows,2304);assert.deepEqual(a.remaining_raw_language_rows,{zh:1008,en:864,mixed:432});assert.equal(a.prior_writer_reviewed_rows,1008);assert.equal(a.prior_label_holds.length,39);assert.equal(a.prior_role_holds.length,24);assert.equal(a.new_continuation_source_rows,14);assert.equal(a.new_source_writer_qa,'PENDING');assert.equal(a.own_literal_name_proxy.adjudicated_echo_fraction,null);assert.equal(receipt.rows_sha256,input.tenthPacket.rows_sha256);
 const all=[input.seed,input.prior,input.part3,input.part4,input.part5,input.part6,input.part7,input.packet,input.newPacket,input.expansionPacket,input.intakePacket,input.fourthPacket,input.fifthPacket,input.sixthPacket,input.seventhPacket,input.eighthPacket,input.ninthPacket,input.tenthPacket].flatMap(p=>p.rows);
 for(const card of input.plan.cards)assert.equal(all.filter(r=>r.topic_id===card.topic_id).length,8,card.topic_id);
 assert.deepEqual(input.tenthPacket.rows.map(r=>r.topic_id),input.plan.cards.map(c=>c.topic_id));assert.equal(new Set(input.tenthPacket.rows.map(r=>r.id)).size,144);
});
test('rehashed remaining-cell,provenance,independence,role corruption and seventeen registered ancestors rejected',async()=>{
 const input=await supplied();for(const [change,error]of [
 [p=>p.registration_main='invented',/registered provenance/],[p=>p.baseline_expansion9_review_sha256='changed',/registered provenance/],[p=>p.baseline_expansion9_path='data/unregistered.json',/registered paths/],[p=>p.selection_basis='NEXT_TOPIC_PER_DOMAIN',/selection/],[p=>p.accepted_rows=144,/cannot mint/],[p=>p.independent_quota_credit=144,/cannot mint/],[p=>p.candidate_prediction_exposures=1,/cannot mint/],[p=>p.new_competition_generations=1,/cannot mint/],[p=>p.source_intake_revision=1,/cannot mint/],[p=>p.resource_verdict='PASS',/simulate independence/],
 [p=>p.rows[0].topic_id=input.plan.cards[1].topic_id,/fixed remaining cell/],[p=>p.rows[0].language='en',/fixed remaining cell/],[p=>p.rows[0].mechanism_family=input.plan.cards[0].train_allocations.find(a=>a.mechanism_family!==p.rows[0].mechanism_family).mechanism_family,/fixed remaining cell/],[p=>p.rows.reverse(),/fixed remaining cell/],[p=>p.rows[0].lineage.writer='independent',/lineage/],[p=>p.rows[0].spans[0].end--,/exact UTF16/],[p=>p.rows[0].factors.action='wrong',/factor\/span/],[p=>p.rows[0].provisional_gold.topics.push(input.topicIds[1]),/provisional positive/],[p=>{const r=p.rows.find(r=>r.mechanism_family==='mf-context-continuation');r.input.recent=[];r.bundle_sha256=seedHash(canonicalJSON(r.input));},/antecedent/],
 ...[input.seed,input.prior,input.part3,input.part4,input.part5,input.part6,input.part7,input.packet,input.newPacket,input.expansionPacket,input.intakePacket,input.fourthPacket,input.fifthPacket,input.sixthPacket,input.seventhPacket,input.eighthPacket,input.ninthPacket].map(old=>[p=>{const r=p.rows[0],o=old.rows[0];r.input=structuredClone(o.input);r.input_sha256=o.input_sha256;r.normalized_current_sha256=o.normalized_current_sha256;r.bundle_sha256=o.bundle_sha256;},/duplicate/])
 ]){const tenthPacket=structuredClone(input.tenthPacket);change(tenthPacket);tenthPacket.rows_sha256=seedHash(canonicalJSON(tenthPacket.rows));assert.throws(()=>auditMechanismMatrixTrainExpansion10({...input,tenthPacket,tenthPacketUtf8:JSON.stringify(tenthPacket)}),error);}
 assert.throws(()=>auditMechanismMatrixTrainExpansion10({...input,topicIds:input.topicIds.slice(0,18)}),/full144/);assert.throws(()=>auditMechanismMatrixTrainExpansion10({...input,tenthPacketUtf8:JSON.stringify({...input.tenthPacket,accepted_rows:1})}),/object\/bytes/);assert.throws(()=>auditMechanismMatrixTrainExpansion10({...input,ninthSourceReviewUtf8:input.ninthSourceReviewUtf8+' '}),/prior writer QA bytes/);
 const qa=JSON.parse(input.priorNinthReviewResultUtf8);qa.audit.accepted_gold_rows=1008;assert.throws(()=>auditMechanismMatrixTrainExpansion10({...input,priorNinthReviewResultUtf8:JSON.stringify(qa)}),/deficit audit/);
});
test('source-only full144 continuation deterministic,pure and cannot mint capability,resources or allowances',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixTrainExpansion10(input),b=auditMechanismMatrixTrainExpansion10(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.original_prior_sources_gold_roles_preserved,true);assert.equal(a.writer_lineage_components,1);assert.equal(a.independent_scenario_count,null);assert.equal(a.qualified_meaningful_families,null);assert.equal(a.qualified_heldout_families,null);for(const k of ['accepted_rows','accepted_gold_rows','independent_quota_credit','candidate_predictions','semantic_evaluations','new_competition_generations'])assert.equal(a[k],0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);assert.equal(a.old_v04_or_sealed_overlap_review,'NOT_PERFORMED_NO_OLD_OR_SEALED_CONTENT_READS');
});

