import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixSourceDeficits} from './mechanism_matrix_source_deficits.mjs';
import {readFile} from 'node:fs/promises';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function supplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),part6Utf8=await read(dir+'mechanism_matrix_train_part6_v0.1.json'),part6ReviewUtf8=await read(dir+'mechanism_matrix_train_part6_review_v0.1.json'),part7Utf8=await read(dir+'mechanism_matrix_train_part7_v0.1.json'),part7ReviewUtf8=await read(dir+'mechanism_matrix_train_part7_review_v0.1.json'),packetUtf8=await read(dir+'mechanism_matrix_train_part8_v0.1.json'),sourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_part8_review_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 const sourceReviewUtf8=await read(dir+'mechanism_matrix_train_part8_review_v0.1.json');
 return {sourceReview,sourceReviewUtf8,packet:JSON.parse(packetUtf8),packetUtf8,part7:JSON.parse(part7Utf8),part7Utf8,part7Review:JSON.parse(part7ReviewUtf8),part7ReviewUtf8,part6:JSON.parse(part6Utf8),part6Utf8,part6Review:JSON.parse(part6ReviewUtf8),part6ReviewUtf8,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}

test('actual registered144-card deficits retain every frozen hold and distinguish raw from qualification',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_SOURCE_DEFICITS_RESULT.json'));
 for(const p of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(p.path)),p.sha256,p.path);
 const a=auditMechanismMatrixSourceDeficits(input);assert.deepEqual(a,receipt.audit);assert.equal(a.cards.length,144);assert.equal(a.raw_rows,432);assert.equal(a.raw_topics,144);assert.equal(a.raw_remaining_train_rows,3024);assert.equal(a.qualified_train_remaining_rows,3456);assert.equal(a.writer_label_hold_ids.length,30);assert.deepEqual(a.writer_role_hold_ids,['ZMR-MATRIX-TRAIN-PART8-026']);assert.equal(a.roles_without_explicit_disposition,378);assert.equal(a.raw_recent_context_rows,42);assert.equal(a.raw_own_name_echo_proxy.rows,30);assert.equal(a.raw_own_name_echo_proxy.adjudicated_echo_fraction,null);assert.equal(a.family_language_confounding_topics,144);assert.deepEqual(a.literal_factor_distinct_count_histograms,{action:{'2':9,'3':135},object:{'3':144},qualifier:{'3':144}});
 for(const c of a.cards){assert.equal(c.raw_remaining_rows,21);assert.deepEqual(c.raw_remaining_languages,{zh:11,en:7,mixed:3});assert.equal(c.missing_nominal_family_ids.length,5);assert.equal(c.remaining_family_language_cells.reduce((n,x)=>n+x.remaining_raw,0),21);assert.equal(c.provisional_neighbors.length,3);assert.equal(c.qualified_meaningful_families,null);assert.equal(c.accepted_rows,0);}
 assert.equal(a.ordinary_dev_remaining_raw_rows,1728);assert.equal(a.challenge_dev_remaining_raw_rows,1728);assert.equal(a.directional_source_cases,0);assert.equal(a.accepted_role_rows,0);assert.equal(a.qualified_context_required_scenarios,0);
});
test('partial universe,forged currentQA bytes and ancestor source/lineage/budget corruption fail',async()=>{
 const input=await supplied();assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,topicIds:input.topicIds.slice(0,18)}),/full144/);assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,sourceReviewUtf8:input.sourceReviewUtf8+' '}),/registered writer QA bytes/);
 const sourceReview=structuredClone(input.sourceReview);sourceReview.records[25].role_review_disposition='PROVISIONAL_WRITER_ROLE_RETAIN';sourceReview.records_sha256=seedHash(canonicalJSON(sourceReview.records));assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,sourceReview,sourceReviewUtf8:JSON.stringify(sourceReview)}),/registered writer QA bytes/);
 const part7=structuredClone(input.part7);part7.rows[0].lineage.writer='invented-independent';assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,part7}),/lineage|digest|object\/bytes/);
 const plan=structuredClone(input.plan);plan.targets.TRAIN.per_topic=3;assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,plan}),/formal quota target changed/);
 const packet=structuredClone(input.packet);packet.new_competition_generations=1;assert.throws(()=>auditMechanismMatrixSourceDeficits({...input,packet}),/cannot mint/);
});
test('source-only deficits are deterministic without qualification,inputs mutation or budget credit',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixSourceDeficits(input),b=auditMechanismMatrixSourceDeficits(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.writer_lineage_components,1);assert.equal(a.authoring_run_ids.length,8);assert.equal(a.independent_scenario_count,null);assert.equal(a.grouped_uncertainty,'UNAVAILABLE_SINGLE_WRITER_COMPONENT_NOT_INDEPENDENT');assert.equal(a.old_v04_credit,0);assert.equal(a.new_matrix_ordinary_dev_rows,0);assert.equal(a.new_matrix_challenge_dev_rows,0);for(const k of ['source_input_revisions','accepted_gold_rows','independent_reviewers','independent_quota_credit','candidate_predictions','semantic_evaluations','new_stable_allocations'])assert.equal(a[k],0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);
});
