/** Source-only quota expansion under registered144-card plan;no Router or I/O. */
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixExpansion2Review} from './mechanism_matrix_expansion2_review.mjs';
const must=(v,m)=>{if(!v)throw Error(m);};
const norm=s=>s.normalize('NFKC').toLowerCase().replace(/\s+/gu,' ').trim();
const grams=s=>{const c=Array.from(norm(s));return new Set(c.length<3?[c.join('')]:c.slice(0,-2).map((_,i)=>c.slice(i,i+3).join('')));};
const dice=(a,b)=>{let n=0;for(const g of a)if(b.has(g))n++;return 2*n/(a.size+b.size||1);};
export function auditMechanismMatrixTrainExpansion3(input){
 const {intakePacket:p,intakePacketUtf8,priorExpansionReviewResultUtf8,plan,topicIds}=input,base=auditMechanismMatrixExpansion2Review(input);
 must(canonicalJSON(JSON.parse(intakePacketUtf8))===canonicalJSON(p),'expansion supplied object/bytes');
 must(canonicalJSON(input.expansionSourceReview)===canonicalJSON(JSON.parse(input.expansionSourceReviewUtf8))&&seedHash(input.expansionSourceReviewUtf8)==='436c848a606fc0a07624698b40ed9a8ee069639b4df402ca51d1d6b7c3f37c85','expansion registered prior writer QA bytes');
 const receipt=JSON.parse(priorExpansionReviewResultUtf8);must(canonicalJSON(receipt.audit)===canonicalJSON(base)&&receipt.source_main==='459d8df037ab4b4b979edd963da1673a2daeb7c9'&&receipt.source_tree==='9a612bfa11a028b228d55de7e31c5794cd7e6131','expansion registered deficit audit');
 must(p.schema==='ZMR-MECHANISM-MATRIX-QUOTA-EXPANSION-1'&&p.evidence_class==='NON_INDEPENDENT_DEVELOPMENT_EVIDENCE'&&p.status==='SOURCE_BYTES_FROZEN_DRAFT_UNACCEPTED_NO_COMPILER_ADMISSION','expansion source evidence');
 must(p.registration_main==='3cc53fbe3562ca54d277f111548724a092e6bfd3'&&p.registration_tree==='8ced4b5f875b0ffe279a94fd7629b7e59a8b314d'&&p.plan_sha256===seedHash(input.planUtf8)&&p.catalog_sha256===plan.catalog_sha256&&p.baseline_expansion2_sha256===seedHash(input.expansionPacketUtf8)&&p.baseline_expansion2_review_sha256===seedHash(input.expansionSourceReviewUtf8)&&p.baseline_prior_review_result_sha256===seedHash(priorExpansionReviewResultUtf8),'expansion registered provenance');
 must(p.plan_path==='data/zero_model_refoundation/development/development_mechanism_matrix_plan_v0.1.json'&&p.baseline_expansion2_path==='data/zero_model_refoundation/development/mechanism_matrix_train_expansion2_v0.1.json'&&p.baseline_expansion2_review_path==='data/zero_model_refoundation/development/mechanism_matrix_train_expansion2_review_v0.1.json'&&p.baseline_prior_review_result_path==='docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION2_REVIEW_RESULT.json','expansion registered paths');
 must(p.selection_basis==='PINNED_THIRD_TOPIC_PER_DOMAIN_FIRST_REMAINING_ALLOCATION_CELLS_NOT_CANDIDATE_ERRORS'&&p.generation_claim==='NONE_NO_STABLE_ALLOCATION_OR_BUDGET_RESET'&&p.source_license==='ORIGINAL_CANDIDATE_WRITER_FICTIONAL_DECLARATION_NOT_INDEPENDENTLY_VERIFIED','expansion selection/license/generation');
 for(const k of ['independent_quota_credit','accepted_rows','candidate_prediction_exposures','semantic_evaluations','new_competition_generations','source_intake_revision'])must(p[k]===0,'expansion cannot mint qualification/evaluation/allowance');
 must(p.writer_id==='candidate-writer'&&p.writer_cohort==='candidate-writer-G0'&&p.source_family==='candidate-writer-G0'&&p.data_qualification==='NOT_QUALIFIED'&&p.capability_verdict==='UNTESTED'&&p.resource_verdict==='NOT_QUALIFIED'&&p.sealed_contents_created===false&&p.saturation_ceiling_claim===false,'expansion cannot simulate independence/qualification');
 must(p.rows.length===54&&p.rows_sha256===seedHash(canonicalJSON(p.rows))&&Number.isFinite(Date.parse(p.frozen_at)),'expansion source freeze/count');
 must(p.near_duplicate_screen.threshold===.55&&p.near_duplicate_screen.scope==='NEW54_PLUS_REGISTERED_MATRIX540_ONLY'&&p.near_duplicate_screen.independent_review===false,'expansion screen scope');
 const priorRows=[input.seed,input.prior,input.part3,input.part4,input.part5,input.part6,input.part7,input.packet].flatMap(x=>x.rows).concat(input.newPacket.rows,input.expansionPacket.rows),hashes=new Set(priorRows.map(r=>r.normalized_current_sha256)),bundles=new Set(priorRows.map(r=>r.bundle_sha256)),literalIds=[],lang={zh:0,en:0,mixed:0};
 for(const [i,r]of p.rows.entries()){
  const card=plan.cards[Math.floor(i/3)*8+2],language=['zh','en','zh'][i%3],family=card.train_allocations[i%3===2?1:0].mechanism_family;
  must(r.id===`ZMR-MATRIX-TRAIN-EXPANSION3-${String(i+1).padStart(3,'0')}`&&r.topic_id===card.topic_id&&r.language===language&&r.mechanism_family===family&&r.split==='TRAIN','expansion fixed allocation');
  must(r.writer_id==='candidate-writer'&&r.writer_cohort==='candidate-writer-G0'&&r.source_family==='candidate-writer-G0'&&r.source_id===r.id+'-original'&&r.scenario_id===r.id+'-scenario'&&r.lineage.writer==='candidate-writer-G0'&&r.lineage.source===r.source_id&&r.lineage.scenario===r.scenario_id&&r.lineage.shared_authoring_run===p.batch_id&&r.lineage.template_review==='UNREVIEWED_POSSIBLE_SHARED_SKELETONS'&&r.lineage.translation_family===null&&r.lineage.paraphrase_family===null&&r.lineage.contrast_family===null,'expansion writer/source lineage');
  must(r.source_status==='ORIGINAL_FICTIONAL_WRITER_DRAFT_NOT_INDEPENDENT_SOURCE'&&r.label_status==='PROVISIONAL_WRITER_LABEL_UNACCEPTED'&&r.reviewer_id==='candidate-writer'&&r.independent_reviewer_count===0&&r.independent_quota_credit===0,'expansion no independent gold');
  must(r.provisional_gold.expected_state==='ASSIGNED'&&canonicalJSON(r.provisional_gold.topics)===canonicalJSON([card.topic_id])&&canonicalJSON(r.provisional_gold.excluded_topics)==='[]'&&r.identifiability==='PENDING_BOUNDARY_AND_INDEPENDENT_ADJUDICATION'&&r.writer_rationale.length>=30,'expansion provisional positive only');
  const b=r.input;must(Object.keys(b).sort().join(',')==='current,recent,title'&&typeof b.current==='string'&&b.current.length>=20&&typeof b.title==='string'&&Array.isArray(b.recent)&&b.recent.every(x=>typeof x==='string'),'expansion source bundle');
  must(r.input_sha256===seedHash(b.current)&&r.normalized_current_sha256===seedHash(norm(b.current))&&r.bundle_sha256===seedHash(canonicalJSON(b)),'expansion source fingerprints');must(!hashes.has(r.normalized_current_sha256)&&!bundles.has(r.bundle_sha256),'expansion unexplained duplicate');hashes.add(r.normalized_current_sha256);bundles.add(r.bundle_sha256);
  for(const role of ['ACTION','OBJECT','QUALIFIER'])must(r.spans.some(s=>s.role===role),'expansion missing role');
  if(family==='mf-context-continuation')must(b.recent.length>0&&r.spans.some(s=>s.role==='ANTECEDENT'&&s.field.startsWith('recent.')),'expansion context antecedent');
  for(const s of r.spans){const t=s.field==='current'?b.current:s.field==='title'?b.title:/^recent\.[0-9]+$/.test(s.field)?b.recent[Number(s.field.slice(7))]:undefined;must(typeof t==='string'&&['ACTION','OBJECT','QUALIFIER','ANTECEDENT'].includes(s.role)&&Number.isSafeInteger(s.start)&&Number.isSafeInteger(s.end)&&s.start>=0&&s.end>s.start&&s.end<=t.length&&t.slice(s.start,s.end)===s.text,'expansion exact UTF16 role');for(const n of [s.start,s.end])must(n===0||n===t.length||!(t.charCodeAt(n-1)>=0xd800&&t.charCodeAt(n-1)<=0xdbff&&t.charCodeAt(n)>=0xdc00&&t.charCodeAt(n)<=0xdfff),'expansion surrogate boundary');}
  must(canonicalJSON(r.factors)===canonicalJSON(Object.fromEntries(['ACTION','OBJECT','QUALIFIER'].map(role=>[role.toLowerCase(),r.spans.find(s=>s.role===role).text])))&&r.frozen_at===p.frozen_at,'expansion factor/span/freeze');
  if([card.name_zh,card.name_en].some(n=>norm(b.current).includes(norm(n))))literalIds.push(r.id);lang[language]++;
 }
 for(const card of plan.cards.filter((c,i)=>i%8===2)){const rr=[...priorRows,...p.rows].filter(r=>r.topic_id===card.topic_id);for(const a of card.train_allocations)for(const language of ['zh','en','mixed'])must(rr.filter(r=>r.language===language&&r.mechanism_family===a.mechanism_family).length<=a.languages[language],'expansion exceeds registered allocation');}
 const all=[...priorRows,...p.rows],g=all.map(r=>grams(r.input.current)),flags=[];for(let i=0;i<all.length;i++)for(let j=Math.max(i+1,540);j<all.length;j++){const score=dice(g[i],g[j]);if(score>=.55)flags.push({first:all[i].id,second:all[j].id,dice:score,disposition:'HOLD_WRITER_SCREEN_NOT_INDEPENDENTLY_REVIEWED'});}
 return {schema:'ZMR-MECHANISM-MATRIX-TRAIN-EXPANSION3-AUDIT-1',evidence_class:p.evidence_class,new_rows:54,new_language_counts:lang,new_topics:0,expanded_topics:18,full_topic_universe:144,combined_raw_topics:144,combined_raw_rows:594,combined_raw_languages:{zh:252,en:198,mixed:144},remaining_raw_train_rows:2862,remaining_raw_language_rows:{zh:1476,en:954,mixed:432},prior_writer_reviewed_rows:base.combined_writer_reviewed_rows,prior_label_holds:base.combined_label_hold_ids,prior_role_holds:base.combined_role_hold_ids,new_source_writer_qa:'PENDING',accepted_rows:0,accepted_gold_rows:0,independent_quota_credit:0,new_continuation_source_rows:p.rows.filter(r=>r.input.recent.length>0).length,own_literal_name_proxy:{rows:literalIds.length,ids:literalIds,adjudicated_echo_fraction:null},new_and_registered_near_duplicate_flags:flags,screen_scope:p.near_duplicate_screen.scope,original_prior_sources_gold_roles_preserved:true,writer_lineage_components:1,independent_scenario_count:null,qualified_meaningful_families:null,qualified_heldout_families:null,source_license:'DECLARATION_ONLY_NOT_INDEPENDENTLY_VERIFIED',old_v04_or_sealed_overlap_review:'NOT_PERFORMED_NO_OLD_OR_SEALED_CONTENT_READS',candidate_predictions:0,semantic_evaluations:0,new_competition_generations:0,remaining_stable_allowance:null,data_qualification:'NOT_QUALIFIED',capability_verdict:'UNTESTED',resource_verdict:'NOT_QUALIFIED',saturation_ceiling_claim:false};
}
