import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixTrainExpansion5} from './mechanism_matrix_train_expansion5.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function supplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),part6Utf8=await read(dir+'mechanism_matrix_train_part6_v0.1.json'),part6ReviewUtf8=await read(dir+'mechanism_matrix_train_part6_review_v0.1.json'),part7Utf8=await read(dir+'mechanism_matrix_train_part7_v0.1.json'),part7ReviewUtf8=await read(dir+'mechanism_matrix_train_part7_review_v0.1.json'),packetUtf8=await read(dir+'mechanism_matrix_train_part8_v0.1.json'),sourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_part8_review_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 const sourceReviewUtf8=await read(dir+'mechanism_matrix_train_part8_review_v0.1.json');
 const newPacketUtf8=await read(dir+'mechanism_matrix_train_expansion1_v0.1.json'),newPacket=JSON.parse(newPacketUtf8),deficitsUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_SOURCE_DEFICITS_RESULT.json');
 const newSourceReview=JSON.parse(await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'));
 const newSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion1_review_v0.1.json'),priorReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION1_REVIEW_RESULT.json'),expansionPacketUtf8=await read(dir+'mechanism_matrix_train_expansion2_v0.1.json'),expansionPacket=JSON.parse(expansionPacketUtf8);
 const expansionSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion2_review_v0.1.json'),expansionSourceReview=JSON.parse(expansionSourceReviewUtf8),priorExpansionReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION2_REVIEW_RESULT.json'),intakePacketUtf8=await read(dir+'mechanism_matrix_train_expansion3_v0.1.json'),intakePacket=JSON.parse(intakePacketUtf8);
 const intakeSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion3_review_v0.1.json'),intakeSourceReview=JSON.parse(intakeSourceReviewUtf8),priorThirdReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION3_REVIEW_RESULT.json'),fourthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion4_v0.1.json'),fourthPacket=JSON.parse(fourthPacketUtf8);
 const fourthSourceReviewUtf8=await read(dir+'mechanism_matrix_train_expansion4_review_v0.1.json'),fourthSourceReview=JSON.parse(fourthSourceReviewUtf8),priorFourthReviewResultUtf8=await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION4_REVIEW_RESULT.json'),fifthPacketUtf8=await read(dir+'mechanism_matrix_train_expansion5_v0.1.json'),fifthPacket=JSON.parse(fifthPacketUtf8);
 return {fifthPacket,fifthPacketUtf8,fourthSourceReview,fourthSourceReviewUtf8,priorFourthReviewResultUtf8,fourthPacket,fourthPacketUtf8,intakeSourceReview,intakeSourceReviewUtf8,priorThirdReviewResultUtf8,intakePacket,intakePacketUtf8,expansionSourceReview,expansionSourceReviewUtf8,priorExpansionReviewResultUtf8,expansionPacket,expansionPacketUtf8,newSourceReviewUtf8,priorReviewResultUtf8,newSourceReview,newPacket,newPacketUtf8,deficitsUtf8,sourceReview,sourceReviewUtf8,packet:JSON.parse(packetUtf8),packetUtf8,part7:JSON.parse(part7Utf8),part7Utf8,part7Review:JSON.parse(part7ReviewUtf8),part7ReviewUtf8,part6:JSON.parse(part6Utf8),part6Utf8,part6Review:JSON.parse(part6ReviewUtf8),part6ReviewUtf8,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}



test('actual source-only fifthTopic missing cells preserve648prior reviews/32label holds/ten role holds',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_EXPANSION5_RESULT.json'));
 for(const p of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(p.path)),p.sha256,p.path);
 assert.equal(seedHash(input.fifthPacketUtf8),'03d941a88aac8ee247cda20b66f2dd8b50837b0579c378078eb90380f0167dcd');const a=auditMechanismMatrixTrainExpansion5(input);assert.deepEqual(a,receipt.audit);assert.equal(a.new_rows,54);assert.deepEqual(a.new_language_counts,{zh:36,en:18,mixed:0});assert.equal(a.expanded_topics,18);assert.equal(a.full_topic_universe,144);assert.equal(a.combined_raw_topics,144);assert.equal(a.combined_raw_rows,702);assert.deepEqual(a.combined_raw_languages,{zh:324,en:234,mixed:144});assert.equal(a.remaining_raw_train_rows,2754);assert.deepEqual(a.remaining_raw_language_rows,{zh:1404,en:918,mixed:432});assert.equal(a.prior_writer_reviewed_rows,648);assert.equal(a.prior_label_holds.length,32);assert.deepEqual(a.prior_role_holds,['ZMR-MATRIX-TRAIN-PART8-026','ZMR-MATRIX-TRAIN-EXPANSION1-049','ZMR-MATRIX-TRAIN-EXPANSION3-034','ZMR-MATRIX-TRAIN-EXPANSION3-049','ZMR-MATRIX-TRAIN-EXPANSION3-050','ZMR-MATRIX-TRAIN-EXPANSION4-012','ZMR-MATRIX-TRAIN-EXPANSION4-024','ZMR-MATRIX-TRAIN-EXPANSION4-030','ZMR-MATRIX-TRAIN-EXPANSION4-036','ZMR-MATRIX-TRAIN-EXPANSION4-054']);assert.equal(a.new_continuation_source_rows,6);assert.equal(a.own_literal_name_proxy.rows,1);assert.equal(a.own_literal_name_proxy.adjudicated_echo_fraction,null);assert.equal(a.new_and_registered_near_duplicate_flags.length,0);assert.equal(a.new_source_writer_qa,'PENDING');assert.equal(receipt.rows_sha256,input.fifthPacket.rows_sha256);
});
test('rehashed source/allocation/provenance/admission corruption and twelve registered ancestor duplicates fail',async()=>{
 const input=await supplied();for(const [change,error]of [
 [p=>p.registration_main='invented',/registered provenance/],[p=>p.baseline_expansion4_review_sha256='changed',/registered provenance/],[p=>p.baseline_expansion4_path='data/unregistered.json',/registered paths/],[p=>p.accepted_rows=54,/cannot mint/],[p=>p.independent_quota_credit=54,/cannot mint/],[p=>p.new_competition_generations=1,/cannot mint/],[p=>p.capability_verdict='PASS',/simulate independence/],[p=>p.rows[0].topic_id=input.plan.cards[1].topic_id,/fixed allocation/],[p=>p.rows[0].language='mixed',/fixed allocation/],[p=>p.rows[0].mechanism_family=input.plan.cards[2].train_allocations[4].mechanism_family,/fixed allocation/],[p=>p.rows[0].lineage.writer='independent',/lineage/],[p=>p.rows[0].spans[0].end--,/exact UTF16/],[p=>p.rows[0].factors.action='wrong',/factor\/span/],[p=>p.rows[0].provisional_gold.topics.push(input.topicIds[0]),/provisional positive/],[p=>{const r=p.rows.find(r=>r.mechanism_family==='mf-context-continuation');r.input.recent=[];r.bundle_sha256=seedHash(canonicalJSON(r.input));},/antecedent/],
 ...[input.seed,input.prior,input.part3,input.part4,input.part5,input.part6,input.part7,input.packet,input.newPacket,input.expansionPacket,input.intakePacket,input.fourthPacket].map(old=>[p=>{const r=p.rows[0],o=old.rows[0];r.input=structuredClone(o.input);r.input_sha256=o.input_sha256;r.normalized_current_sha256=o.normalized_current_sha256;r.bundle_sha256=o.bundle_sha256;},/duplicate/])
 ]){const fifthPacket=structuredClone(input.fifthPacket);change(fifthPacket);fifthPacket.rows_sha256=seedHash(canonicalJSON(fifthPacket.rows));assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,fifthPacket,fifthPacketUtf8:JSON.stringify(fifthPacket)}),error);}
 assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,topicIds:input.topicIds.slice(0,36)}),/full144/);assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,fifthPacketUtf8:JSON.stringify({...input.fifthPacket,accepted_rows:1})}),/object\/bytes/);assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,newSourceReviewUtf8:input.newSourceReviewUtf8+' '}),/prior writer QA bytes/);
 const qa=JSON.parse(input.priorFourthReviewResultUtf8);qa.audit.accepted_gold_rows=648;assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,priorFourthReviewResultUtf8:JSON.stringify(qa)}),/deficit audit/);
 assert.throws(()=>auditMechanismMatrixTrainExpansion5({...input,fourthSourceReviewUtf8:input.fourthSourceReviewUtf8+' '}),/prior writer QA bytes/);
});
test('source-only quota audit deterministic without frozen source mutation or semantic/resource/independent credit',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixTrainExpansion5(input),b=auditMechanismMatrixTrainExpansion5(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.original_prior_sources_gold_roles_preserved,true);assert.equal(a.writer_lineage_components,1);assert.equal(a.independent_scenario_count,null);assert.equal(a.qualified_meaningful_families,null);assert.equal(a.qualified_heldout_families,null);for(const k of ['accepted_rows','accepted_gold_rows','independent_quota_credit','candidate_predictions','semantic_evaluations','new_competition_generations'])assert.equal(a[k],0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);assert.equal(a.old_v04_or_sealed_overlap_review,'NOT_PERFORMED_NO_OLD_OR_SEALED_CONTENT_READS');
});
