import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {canonicalJSON} from './contracts.mjs';
import {seedHash} from './mechanism_matrix_seed.mjs';
import {auditMechanismMatrixTrainPart6} from './mechanism_matrix_train_part6.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url),'utf8');
async function supplied(){
 const dir='data/zero_model_refoundation/development/',planUtf8=await read(dir+'development_mechanism_matrix_plan_v0.1.json'),seedUtf8=await read(dir+'mechanism_matrix_train_seed_v0.1.json'),reviewUtf8=await read(dir+'mechanism_matrix_train_seed_review_v0.1.json'),priorUtf8=await read(dir+'mechanism_matrix_train_part2_v0.1.json'),qaUtf8=await read(dir+'mechanism_matrix_train_part2_review_v0.1.json'),part3Utf8=await read(dir+'mechanism_matrix_train_part3_v0.1.json'),part3ReviewUtf8=await read(dir+'mechanism_matrix_train_part3_review_v0.1.json'),part4Utf8=await read(dir+'mechanism_matrix_train_part4_v0.1.json'),part4ReviewUtf8=await read(dir+'mechanism_matrix_train_part4_review_v0.1.json'),part5Utf8=await read(dir+'mechanism_matrix_train_part5_v0.1.json'),part5ReviewUtf8=await read(dir+'mechanism_matrix_train_part5_review_v0.1.json'),packet=JSON.parse(await read(dir+'mechanism_matrix_train_part6_v0.1.json')),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topicIds=[...catalog.matchAll(/^  - topic_id: (sys\.[a-z_]+\.[a-z_]+)$/gm)].map(m=>m[1]);
 return {packet,part5:JSON.parse(part5Utf8),part5Utf8,part5Review:JSON.parse(part5ReviewUtf8),part5ReviewUtf8,part4:JSON.parse(part4Utf8),part4Utf8,part4Review:JSON.parse(part4ReviewUtf8),part4ReviewUtf8,part3:JSON.parse(part3Utf8),part3Utf8,part3Review:JSON.parse(part3ReviewUtf8),part3ReviewUtf8,prior:JSON.parse(priorUtf8),priorUtf8,qa:JSON.parse(qaUtf8),qaUtf8,seed:JSON.parse(seedUtf8),seedUtf8,review:JSON.parse(reviewUtf8),reviewUtf8,plan:JSON.parse(planUtf8),planUtf8,topicIds};
}
test('actual part6 pins preserve270 prior reviewed rows/nineteen holds and extend raw sources to324/108Topics',async()=>{
 const input=await supplied(),receipt=JSON.parse(await read('docs/zero-model-refoundation-v1/ZMR-03_MECHANISM_MATRIX_TRAIN_PART6_RESULT.json'));for(const pin of [...receipt.input_pins,...receipt.code_pins])assert.equal(seedHash(await read(pin.path)),pin.sha256,pin.path);
 const a=auditMechanismMatrixTrainPart6(input);assert.deepEqual(a,receipt.audit);assert.equal(a.combined_source_rows,324);assert.equal(a.combined_source_topics,108);assert.equal(a.full_topic_universe,144);assert.equal(a.missing_topics.length,36);assert.deepEqual(a.combined_language_counts,{zh:108,en:108,mixed:108});assert.equal(a.remaining_raw_train_rows,3132);assert.deepEqual(a.remaining_raw_language_rows,{zh:1620,en:1044,mixed:468});assert.equal(a.prior_reviewed_rows,270);assert.equal(a.prior_label_holds,19);assert.equal(a.new_continuation_source_rows,3);assert.equal(a.own_literal_name_proxy.rows,6);assert.equal(a.own_literal_name_proxy.adjudicated_echo_fraction,null);assert.equal(a.new_and_registered_near_duplicate_flags.length,0);assert.equal(a.accepted_rows,0);assert.equal(a.independent_quota_credit,0);assert.equal(a.new_source_writer_qa,'PENDING');assert.equal(receipt.rows_sha256,input.packet.rows_sha256);
});
test('rehashed provenance/span/admission corruption and duplicates from all five registered source packets fail',async()=>{
 const input=await supplied();for(const [change,error]of [
  [p=>p.baseline_part5_path='data/unregistered.json',/prior source/],[p=>p.baseline_part5_review_sha256='changed',/prior source/],[p=>p.independent_quota_credit=1,/cannot mint/],[p=>p.accepted_rows=54,/cannot mint/],[p=>p.new_competition_generations=1,/cannot mint/],[p=>p.capability_verdict='PASS',/qualification/],[p=>p.rows[0].topic_id=input.prior.rows[0].topic_id,/allocation/],[p=>p.rows[0].spans[0].end--,/UTF16/],[p=>p.rows[0].factors.object='wrong',/factor\/span/],[p=>p.rows[0].lineage.writer='independent',/lineage/],[p=>p.rows[0].provisional_gold.excluded_topics=[input.topicIds[5]],/labels\/holds/],
  [p=>{const r=p.rows.find(r=>r.mechanism_family==='mf-context-continuation');r.input.recent=[];r.bundle_sha256=seedHash(canonicalJSON(r.input));},/antecedent/],
  ...[input.seed.rows[0],input.prior.rows[0],input.part3.rows[0],input.part4.rows[0],input.part5.rows[0]].map(s=>[p=>{const r=p.rows[0];r.input=structuredClone(s.input);r.input_sha256=s.input_sha256;r.normalized_current_sha256=s.normalized_current_sha256;r.bundle_sha256=s.bundle_sha256;},/duplicate/]),
  [p=>p.near_duplicate_screen.scope='ALL_SEALED_ZERO_OVERLAP',/screen scope/]
 ]){const packet=structuredClone(input.packet);change(packet);packet.rows_sha256=seedHash(canonicalJSON(packet.rows));assert.throws(()=>auditMechanismMatrixTrainPart6({...input,packet}),error);}
 assert.throws(()=>auditMechanismMatrixTrainPart6({...input,topicIds:input.topicIds.slice(0,54)}),/full144/);assert.throws(()=>auditMechanismMatrixTrainPart6({...input,priorUtf8:input.priorUtf8+' '}),/source identity/);assert.throws(()=>auditMechanismMatrixTrainPart6({...input,part5ReviewUtf8:input.part5ReviewUtf8+' '}),/prior source/);
 const qa=structuredClone(input.qa);qa.records[0].writer_comment+=' unregistered object mutation';qa.records_sha256=seedHash(canonicalJSON(qa.records));assert.throws(()=>auditMechanismMatrixTrainPart6({...input,qa}),/object\/bytes/);
});
test('source-only census is deterministic,does not mutate frozen sources or certify mechanisms/resources',async()=>{
 const input=await supplied(),before=canonicalJSON(input),a=auditMechanismMatrixTrainPart6(input),b=auditMechanismMatrixTrainPart6(input);assert.deepEqual(a,b);assert.equal(canonicalJSON(input),before);assert.equal(a.writer_lineage_components,1);assert.equal(a.independent_scenario_count,null);assert.equal(a.qualified_heldout_family_count,null);assert.equal(a.candidate_predictions,0);assert.equal(a.semantic_evaluations,0);assert.equal(a.new_competition_generations,0);assert.equal(a.remaining_stable_allowance,null);assert.equal(a.old_v04_or_sealed_overlap_review,'NOT_PERFORMED_NO_OLD_OR_SEALED_READS');assert.equal(a.data_qualification,'NOT_QUALIFIED');assert.equal(a.capability_verdict,'UNTESTED');assert.equal(a.resource_verdict,'NOT_QUALIFIED');assert.equal(a.saturation_ceiling_claim,false);
});
