import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {parsePinnedCatalog} from './a1_compile.mjs';
import {fingerprintBundle,screenNearDuplicates} from './fingerprints.mjs';
const ROOT=new URL('../../',import.meta.url),D='data/zero_model_refoundation/development/',path=D+'provisional_safety_v0.4_remaining.json';
const read=p=>readFile(new URL(p,ROOT)),json=async p=>JSON.parse(await read(p)),sha=x=>createHash('sha256').update(x).digest('hex');

test('remaining252 physical inputs complete the336-row development safety target without satisfying formal data qualification',async()=>{
 const s=await json(path),seed=await json(D+'provisional_safety_v0.4_seed.json'),m=await json(D+'provisional_ordinary_dev_v0.4_manifest.json'),p=await json(m.plan_path),status=await json('status/ZERO_MODEL_REFOUNDATION_STATUS.json');
 assert.equal(sha(await read(D+'provisional_safety_v0.4_seed.json')),'7f9a5eaf074108e69b702bf395717d926502169ab5532c040373db7395bbacad');assert.equal(seed.rows.length,84);assert.equal(s.rows.length,252);assert.equal(s.row_count,252);assert.equal(s.pairs.length,72);assert.equal(s.pair_count,72);assert.equal(m.safety_slices.length,2);assert.equal(m.safety_slices[1].path,path);assert.equal(m.safety_slices[1].sha256,sha(await read(path)));
 const all=[...seed.rows,...s.rows],pairs=[...seed.pairs,...s.pairs];assert.equal(all.length,p.target_safety_rows_total);assert.equal(all.length,336);assert.equal(new Set(all.map(r=>r.id)).size,336);
 for(const split of ['TUNE_PROVISIONAL','CAL_PROVISIONAL']){const rows=all.filter(r=>r.split===split),ps=pairs.filter(r=>r.split===split),counts={rows:rows.length,control_rows:rows.filter(r=>r.kind==='control').length,context_required_pairs:ps.filter(p=>p.kind==='context_required').length,context_invariance_pairs:ps.filter(p=>p.kind==='context_invariance').length,multi_rows:rows.filter(r=>r.kind==='multi').length};assert.deepEqual(counts,{rows:168,control_rows:48,context_required_pairs:24,context_invariance_pairs:24,multi_rows:24});assert.deepEqual(m.safety_by_split[split],counts);assert.deepEqual(Object.fromEntries(['zh','en','mixed'].map(l=>[l,rows.filter(r=>r.language===l).length])),{zh:56,en:56,mixed:56});assert.deepEqual(m.safety_target_shortfall[split],{control_rows:0,context_required_pairs:0,context_invariance_pairs:0,multi_rows:0});}
 assert.equal(m.safety_target_shortfall.remaining_physical_rows,0);assert.equal(m.status,'DEVELOPMENT_AUTHORING_TARGET_FROZEN_ORDINARY_AND_SAFETY_NOT_QUALIFIED');assert(m.qualification_conflicts.includes('FORMAL_SAFETY_QUOTA_SHORTFALL'));assert(m.qualification_conflicts.includes('ORDINARY_QUOTA_SHORTFALL'));assert(m.qualification_conflicts.includes('SINGLE_WRITER_PROVISIONAL_SOURCE_AND_MECHANISM_REVIEW_INCOMPLETE'));
 assert.equal(s.evidence_class,'NON_INDEPENDENT_DEVELOPMENT_EVIDENCE');for(const f of ['candidate_prediction_exposures','semantic_evaluations','independent_source_cohorts','qualification_credit_rows','independent_pair_scenarios'])assert.equal(s[f],0);assert.equal(s.lineage_component_count,1);assert.equal(s.formal_cross_split_writer_conflict,true);assert.equal(s.gold_review,'NOT_PROVISIONED');assert.equal(s.source_review,'NOT_PROVISIONED');assert.equal(s.held_out_mechanism_status,'NOT_ADJUDICATED_NO_PASS');assert.equal(m.grouped_validation,'UNAVAILABLE_SINGLE_WRITER_LINEAGE_COMPONENT');assert.equal(m.calibration_admission,'NOT_ADMITTED_PARTIAL_DATA');assert.equal(m.splits.CAL_PROVISIONAL.candidate_prediction_exposures,0);assert.equal(m.stable_competition_admission,'HOLD_PENDING_ACCOUNTING_RECONCILIATION');
 assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_safety_rows,336);assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_safety_remaining_planned_rows,0);assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_status,m.status);assert.equal(status.rounds['ZMR-06'].remaining_stable_configuration_allowance,null);assert.equal(status.capability_verdict,'UNTESTED');assert.equal(status.resource_verdict,'NOT_QUALIFIED');assert.equal(m.data_qualification,'NOT_QUALIFIED');
});

test('remaining safety inputs preserve authored full bundles, provisional object spans and concrete same-split pair identity',async()=>{
 const s=await json(path),catalog=await read('catalog/system_topic_catalog_v0.2.yaml'),topics=new Set(parsePinnedCatalog(catalog).map(t=>t.id)),rows=new Map(s.rows.map(r=>[r.id,r]));assert.equal(s.catalog_sha256,sha(catalog));assert.equal(rows.size,252);
 for(const r of s.rows){assert.equal(r.row_id,r.id);assert.equal(r.frozen_at,s.frozen_at);assert.equal(r.writer_cohort,'candidate-writer-G0');assert.equal(r.source_family,'candidate-writer-G0');assert.equal(r.writer_id,'candidate-writer-G0');assert.equal(r.generation_id,'G0_DEV');assert.equal(r.qualification_credit_rows,0);assert.equal(r.catalog_sha256,s.catalog_sha256);assert.equal(r.exposure,r.split==='TUNE_PROVISIONAL'?'PUBLIC_TUNE':'PUBLIC_CAL');assert.equal(r.review_status,'CANDIDATE_WRITER_UNREVIEWED');assert.equal(r.identifiability_state,'UNREVIEWED');assert.equal(r.source_license_status,'ORIGINAL_CANDIDATE_WRITER_PROVISIONAL');assert.equal(r.span_offset_unit,'UTF16_CODE_UNITS');assert.deepEqual(r.fingerprints,fingerprintBundle({current:r.current,title:r.title,recent:r.recent}));assert.equal(new Set(r.provisional_gold_topics).size,r.provisional_gold_topics.length);assert(r.provisional_gold_topics.every(t=>topics.has(t)));assert.deepEqual(r.excluded_topics,[]);
  if(r.expected_state==='DEFER'){assert.deepEqual(r.provisional_gold_topics,[]);assert.deepEqual(r.provisional_evidence_spans,[]);}else{assert.equal(r.expected_state,'ASSIGNED');assert.equal(r.provisional_gold_topics.length,r.kind==='multi'?2:1);assert(r.provisional_evidence_spans.length>=2);}
  if(r.kind==='control')assert.equal(r.expected_state,'DEFER');if(r.language==='mixed')assert(/\p{Script=Han}/u.test(r.current)&&/[A-Za-z]/u.test(r.current));for(const span of r.provisional_evidence_spans){const text=span.source==='recent'?r.recent[span.recent_index]:r[span.source];assert.equal(typeof text,'string');assert(span.start>=0&&span.end>span.start&&span.end<=text.length);assert.equal(text.slice(span.start,span.end),span.text);}
 }
 const seen=new Set();for(const p of s.pairs){assert(!seen.has(p.id));seen.add(p.id);const a=rows.get(p.base_id),b=rows.get(p.variant_id);assert(a&&b);assert.equal(a.kind,p.kind);assert.equal(b.kind,p.kind);assert.equal(a.split,p.split);assert.equal(b.split,p.split);assert.equal(a.current,b.current);assert.equal(a.scenario_family,p.id);assert.equal(b.scenario_family,p.id);assert.equal(a.contrast_family,b.contrast_family);assert.equal(a.template_family,b.template_family);assert.equal(a.fingerprints.current_sha256,b.fingerprints.current_sha256);assert.notEqual(a.fingerprints.bundle_sha256,b.fingerprints.bundle_sha256);assert.equal(p.independent_scenarios,0);assert.equal(a.expected_state,'ASSIGNED');assert.equal(b.title,'');assert.deepEqual(b.recent,[]);
  if(p.kind==='context_required'){assert.equal(p.operation,'DELETE_TITLE_AND_ALL_RECENT');assert.equal(b.expected_state,'DEFER');assert.deepEqual(b.provisional_gold_topics,[]);assert(a.provisional_evidence_spans.some(x=>x.source==='recent'));}else{assert.equal(p.provisional_expectation,'COMPLETE_NATIVE_OUTPUT_IDENTICAL');assert.deepEqual(a.provisional_gold_topics,b.provisional_gold_topics);assert.equal(a.expected_state,b.expected_state);}
 }
 assert.equal(s.rows.filter(r=>r.kind.startsWith('context')).length,s.pairs.length*2);
});

test('remaining safety public screening reproduces all flags without removing context variants or claiming sealed review',async()=>{
 const s=await json(path),seed=await json(D+'provisional_safety_v0.4_seed.json'),screen=s.public_screen,prior=[];assert.deepEqual(screen.prior_paths,[...seed.public_screen.prior_paths,D+'provisional_safety_v0.4_seed.json']);assert.equal(screen.threshold,.55);assert.equal(screen.gram_size,3);assert.equal(screen.prior_rows,3406);
 for(const p of screen.prior_paths){assert(p.startsWith(D+'provisional_')&&p.endsWith('.json'));const n=p.slice(D.length).replace(/^provisional_/,'').replace(/\.json$/,'');for(const r of (await json(p)).rows??[])if(typeof r.current==='string')prior.push({id:n+'/'+r.id,split:r.split??'PUBLIC_DEV_UNQUALIFIED',scenario:r.scenario_family??r.id,input:{current:r.current,title:r.title??'',recent:r.recent??[]}});}
 const newIds=new Set(s.rows.map(r=>r.id));assert.equal(prior.length,3406);const flags=screenNearDuplicates([...prior,...s.rows.map(r=>({id:r.id,split:r.split,scenario:r.scenario_family,input:{current:r.current,title:r.title,recent:r.recent}}))],{threshold:.55,gram_size:3}).flags.filter(f=>newIds.has(f.left)||newIds.has(f.right));assert.deepEqual(flags,screen.flags);assert.equal(flags.length,32);assert(flags.every(f=>f.same_scenario&&!f.cross_split&&!f.exact_form));assert.equal(screen.review_status,'UNREVIEWED');assert.equal(screen.sealed_test_fingerprints_available,false);assert.equal(screen.no_sealed_overlap_claim,false);assert.equal(screen.legitimate_context_pairs_are_not_current_only_duplicates,true);
 const m=await json(D+'provisional_ordinary_dev_v0.4_manifest.json');assert.equal(m.source_review.safety_public_similarity_flags,seed.public_screen.flags.length+flags.length);assert.equal(m.source_review.safety_public_similarity_flags,43);
});
