import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fingerprintBundle,screenNearDuplicates} from './fingerprints.mjs';
import {parsePinnedCatalog} from './a1_compile.mjs';
const ROOT=new URL('../../',import.meta.url),D='data/zero_model_refoundation/development/';
const read=p=>readFile(new URL(p,ROOT)),json=async p=>JSON.parse(await read(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const seedPath=D+'provisional_safety_v0.4_seed.json';

test('safety seed structure preserves84 physical inputs,24 pairs,252-row planned shortfall and zero qualification',async()=>{
 const s=await json(seedPath),m=await json(D+'provisional_ordinary_dev_v0.4_manifest.json'),status=await json('status/ZERO_MODEL_REFOUNDATION_STATUS.json');
 assert.equal(s.row_count,84);assert.equal(s.rows.length,84);assert.equal(s.pair_count,24);assert.equal(s.pairs.length,24);assert.equal(s.evidence_class,'NON_INDEPENDENT_DEVELOPMENT_EVIDENCE');
 for(const f of ['candidate_prediction_exposures','semantic_evaluations','independent_source_cohorts','qualification_credit_rows','independent_pair_scenarios'])assert.equal(s[f],0);
 assert.equal(s.source_review,'NOT_PROVISIONED');assert.equal(s.gold_review,'NOT_PROVISIONED');assert.equal(s.lineage_component_count,1);assert.equal(s.formal_cross_split_writer_conflict,true);assert.equal(s.held_out_mechanism_status,'NOT_ADJUDICATED_NO_PASS');
 assert.equal(m.safety_slices.length,1);assert.equal(m.safety_slices[0].path,seedPath);assert.equal(m.safety_slices[0].sha256,sha(await read(seedPath)));assert.equal(m.safety_slices[0].rows,84);assert.equal(m.safety_slices[0].pairs,24);assert.deepEqual(m.safety_by_split,s.counts_by_split);assert.equal(m.safety_target_shortfall.remaining_physical_rows,252);
 for(const split of ['TUNE_PROVISIONAL','CAL_PROVISIONAL']){const r=s.rows.filter(r=>r.split===split),pairs=s.pairs.filter(p=>p.split===split);assert.equal(r.length,42);assert.equal(r.filter(r=>r.kind==='control').length,12);assert.equal(r.filter(r=>r.kind==='multi').length,6);assert.equal(pairs.filter(p=>p.kind==='context_required').length,6);assert.equal(pairs.filter(p=>p.kind==='context_invariance').length,6);assert.deepEqual(m.safety_target_shortfall[split],{control_rows:36,context_required_pairs:18,context_invariance_pairs:18,multi_rows:18});}
 assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_safety_rows,84);assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_safety_remaining_planned_rows,252);assert.equal(status.rounds['ZMR-03'].ordinary_dev_v04_safety_prediction_exposures,0);assert.equal(status.rounds['ZMR-06'].remaining_stable_configuration_allowance,null);
 assert.equal(m.data_qualification,'NOT_QUALIFIED');assert.equal(status.capability_verdict,'UNTESTED');assert.equal(status.resource_verdict,'NOT_QUALIFIED');assert.equal(m.calibration_admission,'NOT_ADMITTED_PARTIAL_DATA');assert.equal(m.splits.CAL_PROVISIONAL.candidate_prediction_exposures,0);
});

test('every safety input pins real full-bundle fingerprints, legal provisional sets and UTF16 source spans',async()=>{
 const s=await json(seedPath),bytes=await read('catalog/system_topic_catalog_v0.2.yaml'),ids=new Set(parsePinnedCatalog(bytes).map(t=>t.id)),seen=new Set();assert.equal(s.catalog_sha256,sha(bytes));
 for(const r of s.rows){assert(!seen.has(r.id));seen.add(r.id);assert.equal(r.id,r.row_id);assert.equal(r.catalog_sha256,s.catalog_sha256);assert.equal(r.frozen_at,s.frozen_at);assert.equal(r.writer_id,'candidate-writer-G0');assert.equal(r.writer_cohort,'candidate-writer-G0');assert.equal(r.source_family,'candidate-writer-G0');assert.equal(r.generation_id,'G0_DEV');assert.equal(r.qualification_credit_rows,0);assert.equal(r.source_license_status,'ORIGINAL_CANDIDATE_WRITER_PROVISIONAL');assert.equal(r.review_status,'CANDIDATE_WRITER_UNREVIEWED');assert.equal(r.annotation_state,'UNREVIEWED_PROVISIONAL');assert.equal(r.identifiability_state,'UNREVIEWED');assert.equal(r.span_offset_unit,'UTF16_CODE_UNITS');assert.equal(r.exposure,r.split==='CAL_PROVISIONAL'?'PUBLIC_CAL':'PUBLIC_TUNE');
  assert(['zh','en','mixed'].includes(r.language));assert.equal(new Set(r.provisional_gold_topics).size,r.provisional_gold_topics.length);assert(r.provisional_gold_topics.every(t=>ids.has(t)));assert.deepEqual(r.excluded_topics,[]);assert(['ASSIGNED','DEFER'].includes(r.expected_state));assert.deepEqual(r.fingerprints,fingerprintBundle({current:r.current,title:r.title,recent:r.recent}));
  if(r.expected_state==='DEFER'){assert.deepEqual(r.provisional_gold_topics,[]);assert.deepEqual(r.provisional_evidence_spans,[]);}else{assert(r.provisional_gold_topics.length>=1);assert(r.provisional_evidence_spans.length>=2);}
  if(r.kind==='multi')assert.equal(r.provisional_gold_topics.length,2);if(r.kind==='control'){assert.equal(r.expected_state,'DEFER');assert(r.translation_family);}
  for(const span of r.provisional_evidence_spans){const source=span.source==='recent'?r.recent[span.recent_index]:r[span.source];assert.equal(typeof source,'string');assert(span.start>=0&&span.end>span.start&&span.end<=source.length);assert.equal(source.slice(span.start,span.end),span.text);}
 }
 for(const split of ['TUNE_PROVISIONAL','CAL_PROVISIONAL']){const controls=s.rows.filter(r=>r.split===split&&r.kind==='control');assert.equal(new Set(controls.map(r=>r.scenario_family)).size,4);assert.equal(new Set(controls.map(r=>r.translation_family)).size,4);assert.deepEqual(Object.fromEntries(['zh','en','mixed'].map(l=>[l,s.rows.filter(r=>r.split===split&&r.language===l).length])),{zh:14,en:14,mixed:14});}
});

test('context pair graph keeps concrete deletion variants in their source split without counting them as independent scenarios',async()=>{
 const s=await json(seedPath),rows=new Map(s.rows.map(r=>[r.id,r])),seen=new Set();
 for(const p of s.pairs){assert(!seen.has(p.id));seen.add(p.id);const a=rows.get(p.base_id),b=rows.get(p.variant_id);assert(a&&b);assert.notEqual(a.id,b.id);assert.equal(a.split,p.split);assert.equal(b.split,p.split);assert.equal(a.kind,p.kind);assert.equal(b.kind,p.kind);assert.equal(a.current,b.current);assert.equal(a.scenario_family,p.id);assert.equal(b.scenario_family,p.id);assert.equal(a.contrast_family,b.contrast_family);assert.equal(a.template_family,b.template_family);assert.equal(a.writer_cohort,b.writer_cohort);assert.notEqual(a.fingerprints.bundle_sha256,b.fingerprints.bundle_sha256);assert.equal(a.fingerprints.current_sha256,b.fingerprints.current_sha256);assert.deepEqual(b.recent,[]);assert.equal(b.title,'');assert.equal(p.independent_scenarios,0);assert.equal(a.expected_state,'ASSIGNED');
  if(p.kind==='context_required'){assert.equal(p.operation,'DELETE_TITLE_AND_ALL_RECENT');assert.equal(b.expected_state,'DEFER');assert.deepEqual(b.provisional_gold_topics,[]);assert(a.provisional_evidence_spans.some(x=>x.source==='recent'));}else{assert.equal(p.operation,'DELETE_MISLEADING_TITLE_AND_RECENT');assert.equal(p.provisional_expectation,'COMPLETE_NATIVE_OUTPUT_IDENTICAL');assert.equal(a.expected_state,b.expected_state);assert.deepEqual(a.provisional_gold_topics,b.provisional_gold_topics);}
 }
 assert.equal(s.rows.filter(r=>r.kind.startsWith('context')).length,s.pairs.length*2);
});

test('public safety screening preserves all flags including legitimate context relations without claiming adjudication',async()=>{
 const s=await json(seedPath),screen=s.public_screen,prior=[];
 const revision=s.pre_intake_revision;assert.equal(revision.round,1);assert.equal(revision.maximum_pre_prediction_intake_revisions,2);assert.equal(revision.candidate_prediction_exposures,0);assert.equal(revision.router_repairs_spent,0);assert.equal(revision.rejected_flag.exact_form,'bundle_sha256');assert.equal(revision.rejected_flag.cross_split,true);assert.equal(revision.rejected_flag.right,'safety-v04-cal-001');assert.equal(s.version,'0.4.1-safety-seed');
 const restored=structuredClone(s);restored.version=revision.original_version;restored.frozen_at=revision.original_frozen_at;for(const r of restored.rows)r.frozen_at=revision.original_frozen_at;restored.rows[restored.rows.findIndex(r=>r.id===revision.rejected_original_row.id)]=revision.rejected_original_row;restored.public_screen.flags=revision.original_public_flags;delete restored.pre_intake_revision;assert.equal(sha(JSON.stringify(restored,null,2)+'\n'),revision.original_dataset_sha256);assert.equal(revision.original_dataset_sha256,'fb1d243d93a6fdf51bebf34ac1f3eee414a41b0be55da2f6fe2b469384ba0393');assert.equal(revision.original_public_flags.length,12);
 const names=['train_v0.1','train_v0.2','train_v0.3','tune_v0.1','cal_v0.1','a7_dev_v0.1','a4_triads_v0.1','a4_train_v0.1','a4_challenge_v0.1','a4_positive_challenge_v0.1','a5_challenge_v0.1','a5_repair_dev_v0.1','a5_r1_challenge_v0.1','a6_complement_challenge_v0.1','a6_r1_repair_dev_v0.1','a6_r2_challenge_v0.1','challenge_v0.1','challenge_v0.2','challenge_v0.3','challenge_v0.4','challenge_v0.5','challenge_v0.6','safety_seed_v0.1','safety_seed_v0.2','safety_seed_v0.3','safety_seed_v0.4','role_challenge_v0.1','h1_recall_dev_v0.1','a5_chart_dev_v0.1','a4_role_dev_v0.1','a1_balanced_dev_v0.1','train_v0.4_slice1','train_v0.4_slice2','train_v0.4_slice3','train_v0.4_slice4','train_v0.4_slice5','tune_v0.4_slice1','tune_v0.4_slice2','tune_v0.4_slice3','tune_v0.4_slice4','tune_v0.4_slice5','cal_v0.4_slice1','cal_v0.4_remaining'];
 assert.deepEqual(screen.prior_paths,names.map(n=>D+'provisional_'+n+'.json'));
 for(const n of names)for(const r of (await json(D+'provisional_'+n+'.json')).rows??[])if(typeof r.current==='string')prior.push({id:n+'/'+r.id,split:r.split??'PUBLIC_DEV_UNQUALIFIED',scenario:r.scenario_family??r.id,input:{current:r.current,title:r.title??'',recent:r.recent??[]}});
 const inputRows=s.rows.map(r=>({id:r.id,split:r.split,scenario:r.scenario_family,input:{current:r.current,title:r.title,recent:r.recent}})),ids=new Set(s.rows.map(r=>r.id));assert.equal(prior.length,3322);assert.equal(screen.prior_rows,prior.length);assert.equal(screen.threshold,.55);assert.equal(screen.gram_size,3);
 const flags=screenNearDuplicates([...prior,...inputRows],{threshold:screen.threshold,gram_size:screen.gram_size}).flags.filter(f=>ids.has(f.left)||ids.has(f.right));assert.deepEqual(flags,screen.flags);assert.equal(screen.review_status,'UNREVIEWED');assert.equal(screen.classification,'REVIEW_FLAGS_ONLY_NO_EQUIVALENCE_OR_ELIGIBILITY');assert.equal(screen.sealed_test_fingerprints_available,false);assert.equal(screen.no_sealed_overlap_claim,false);assert.equal(screen.legitimate_context_pairs_are_not_current_only_duplicates,true);
 const m=await json(D+'provisional_ordinary_dev_v0.4_manifest.json');assert.equal(m.source_review.safety_public_similarity_flags,flags.length);assert(m.qualification_conflicts.includes('SAFETY_GOLD_AND_PUBLIC_SIMILARITY_FLAGS_UNREVIEWED'));
});
